// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: discopanel/v1/admin.proto

package discopanelv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nickheyer/discopanel/pkg/proto/discopanel/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "discopanel.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminServiceListWhitelistEntriesProcedure is the fully-qualified name of the AdminService's
	// ListWhitelistEntries RPC.
	AdminServiceListWhitelistEntriesProcedure = "/discopanel.v1.AdminService/ListWhitelistEntries"
	// AdminServiceAddWhitelistEntryProcedure is the fully-qualified name of the AdminService's
	// AddWhitelistEntry RPC.
	AdminServiceAddWhitelistEntryProcedure = "/discopanel.v1.AdminService/AddWhitelistEntry"
	// AdminServiceRemoveWhitelistEntryProcedure is the fully-qualified name of the AdminService's
	// RemoveWhitelistEntry RPC.
	AdminServiceRemoveWhitelistEntryProcedure = "/discopanel.v1.AdminService/RemoveWhitelistEntry"
	// AdminServiceApplyWhitelistProcedure is the fully-qualified name of the AdminService's
	// ApplyWhitelist RPC.
	AdminServiceApplyWhitelistProcedure = "/discopanel.v1.AdminService/ApplyWhitelist"
	// AdminServicePullWhitelistProcedure is the fully-qualified name of the AdminService's
	// PullWhitelist RPC.
	AdminServicePullWhitelistProcedure = "/discopanel.v1.AdminService/PullWhitelist"
	// AdminServiceBanPlayerProcedure is the fully-qualified name of the AdminService's BanPlayer RPC.
	AdminServiceBanPlayerProcedure = "/discopanel.v1.AdminService/BanPlayer"
	// AdminServiceUnbanPlayerProcedure is the fully-qualified name of the AdminService's UnbanPlayer
	// RPC.
	AdminServiceUnbanPlayerProcedure = "/discopanel.v1.AdminService/UnbanPlayer"
	// AdminServiceGetServerMotdProcedure is the fully-qualified name of the AdminService's
	// GetServerMotd RPC.
	AdminServiceGetServerMotdProcedure = "/discopanel.v1.AdminService/GetServerMotd"
	// AdminServiceUpdateServerMotdProcedure is the fully-qualified name of the AdminService's
	// UpdateServerMotd RPC.
	AdminServiceUpdateServerMotdProcedure = "/discopanel.v1.AdminService/UpdateServerMotd"
)

// AdminServiceClient is a client for the discopanel.v1.AdminService service.
type AdminServiceClient interface {
	// List whitelist entries stored in the panel
	ListWhitelistEntries(context.Context, *connect.Request[v1.ListWhitelistEntriesRequest]) (*connect.Response[v1.ListWhitelistEntriesResponse], error)
	// Add a player to the panel-side whitelist
	AddWhitelistEntry(context.Context, *connect.Request[v1.AddWhitelistEntryRequest]) (*connect.Response[v1.AddWhitelistEntryResponse], error)
	// Remove a player from the panel-side whitelist
	RemoveWhitelistEntry(context.Context, *connect.Request[v1.RemoveWhitelistEntryRequest]) (*connect.Response[v1.RemoveWhitelistEntryResponse], error)
	// Converge selected servers to the panel-side whitelist via RCON
	ApplyWhitelist(context.Context, *connect.Request[v1.ApplyWhitelistRequest]) (*connect.Response[v1.ApplyWhitelistResponse], error)
	// Read the current whitelist from a server via RCON and import it into the panel
	PullWhitelist(context.Context, *connect.Request[v1.PullWhitelistRequest]) (*connect.Response[v1.PullWhitelistResponse], error)
	// Ban a player on the selected servers via RCON
	BanPlayer(context.Context, *connect.Request[v1.BanPlayerRequest]) (*connect.Response[v1.BanPlayerResponse], error)
	// Unban a player on the selected servers via RCON
	UnbanPlayer(context.Context, *connect.Request[v1.UnbanPlayerRequest]) (*connect.Response[v1.UnbanPlayerResponse], error)
	// Read the MOTD and icon from a server's server.properties / icon.png
	GetServerMotd(context.Context, *connect.Request[v1.GetServerMotdRequest]) (*connect.Response[v1.GetServerMotdResponse], error)
	// Write the MOTD and/or icon to a server (server must be stopped to take effect on restart)
	UpdateServerMotd(context.Context, *connect.Request[v1.UpdateServerMotdRequest]) (*connect.Response[v1.UpdateServerMotdResponse], error)
}

// NewAdminServiceClient constructs a client for the discopanel.v1.AdminService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := v1.File_discopanel_v1_admin_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		listWhitelistEntries: connect.NewClient[v1.ListWhitelistEntriesRequest, v1.ListWhitelistEntriesResponse](
			httpClient,
			baseURL+AdminServiceListWhitelistEntriesProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListWhitelistEntries")),
			connect.WithClientOptions(opts...),
		),
		addWhitelistEntry: connect.NewClient[v1.AddWhitelistEntryRequest, v1.AddWhitelistEntryResponse](
			httpClient,
			baseURL+AdminServiceAddWhitelistEntryProcedure,
			connect.WithSchema(adminServiceMethods.ByName("AddWhitelistEntry")),
			connect.WithClientOptions(opts...),
		),
		removeWhitelistEntry: connect.NewClient[v1.RemoveWhitelistEntryRequest, v1.RemoveWhitelistEntryResponse](
			httpClient,
			baseURL+AdminServiceRemoveWhitelistEntryProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RemoveWhitelistEntry")),
			connect.WithClientOptions(opts...),
		),
		applyWhitelist: connect.NewClient[v1.ApplyWhitelistRequest, v1.ApplyWhitelistResponse](
			httpClient,
			baseURL+AdminServiceApplyWhitelistProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ApplyWhitelist")),
			connect.WithClientOptions(opts...),
		),
		pullWhitelist: connect.NewClient[v1.PullWhitelistRequest, v1.PullWhitelistResponse](
			httpClient,
			baseURL+AdminServicePullWhitelistProcedure,
			connect.WithSchema(adminServiceMethods.ByName("PullWhitelist")),
			connect.WithClientOptions(opts...),
		),
		banPlayer: connect.NewClient[v1.BanPlayerRequest, v1.BanPlayerResponse](
			httpClient,
			baseURL+AdminServiceBanPlayerProcedure,
			connect.WithSchema(adminServiceMethods.ByName("BanPlayer")),
			connect.WithClientOptions(opts...),
		),
		unbanPlayer: connect.NewClient[v1.UnbanPlayerRequest, v1.UnbanPlayerResponse](
			httpClient,
			baseURL+AdminServiceUnbanPlayerProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UnbanPlayer")),
			connect.WithClientOptions(opts...),
		),
		getServerMotd: connect.NewClient[v1.GetServerMotdRequest, v1.GetServerMotdResponse](
			httpClient,
			baseURL+AdminServiceGetServerMotdProcedure,
			connect.WithSchema(adminServiceMethods.ByName("GetServerMotd")),
			connect.WithClientOptions(opts...),
		),
		updateServerMotd: connect.NewClient[v1.UpdateServerMotdRequest, v1.UpdateServerMotdResponse](
			httpClient,
			baseURL+AdminServiceUpdateServerMotdProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateServerMotd")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	listWhitelistEntries *connect.Client[v1.ListWhitelistEntriesRequest, v1.ListWhitelistEntriesResponse]
	addWhitelistEntry    *connect.Client[v1.AddWhitelistEntryRequest, v1.AddWhitelistEntryResponse]
	removeWhitelistEntry *connect.Client[v1.RemoveWhitelistEntryRequest, v1.RemoveWhitelistEntryResponse]
	applyWhitelist       *connect.Client[v1.ApplyWhitelistRequest, v1.ApplyWhitelistResponse]
	pullWhitelist        *connect.Client[v1.PullWhitelistRequest, v1.PullWhitelistResponse]
	banPlayer            *connect.Client[v1.BanPlayerRequest, v1.BanPlayerResponse]
	unbanPlayer          *connect.Client[v1.UnbanPlayerRequest, v1.UnbanPlayerResponse]
	getServerMotd        *connect.Client[v1.GetServerMotdRequest, v1.GetServerMotdResponse]
	updateServerMotd     *connect.Client[v1.UpdateServerMotdRequest, v1.UpdateServerMotdResponse]
}

// ListWhitelistEntries calls discopanel.v1.AdminService.ListWhitelistEntries.
func (c *adminServiceClient) ListWhitelistEntries(ctx context.Context, req *connect.Request[v1.ListWhitelistEntriesRequest]) (*connect.Response[v1.ListWhitelistEntriesResponse], error) {
	return c.listWhitelistEntries.CallUnary(ctx, req)
}

// AddWhitelistEntry calls discopanel.v1.AdminService.AddWhitelistEntry.
func (c *adminServiceClient) AddWhitelistEntry(ctx context.Context, req *connect.Request[v1.AddWhitelistEntryRequest]) (*connect.Response[v1.AddWhitelistEntryResponse], error) {
	return c.addWhitelistEntry.CallUnary(ctx, req)
}

// RemoveWhitelistEntry calls discopanel.v1.AdminService.RemoveWhitelistEntry.
func (c *adminServiceClient) RemoveWhitelistEntry(ctx context.Context, req *connect.Request[v1.RemoveWhitelistEntryRequest]) (*connect.Response[v1.RemoveWhitelistEntryResponse], error) {
	return c.removeWhitelistEntry.CallUnary(ctx, req)
}

// ApplyWhitelist calls discopanel.v1.AdminService.ApplyWhitelist.
func (c *adminServiceClient) ApplyWhitelist(ctx context.Context, req *connect.Request[v1.ApplyWhitelistRequest]) (*connect.Response[v1.ApplyWhitelistResponse], error) {
	return c.applyWhitelist.CallUnary(ctx, req)
}

// PullWhitelist calls discopanel.v1.AdminService.PullWhitelist.
func (c *adminServiceClient) PullWhitelist(ctx context.Context, req *connect.Request[v1.PullWhitelistRequest]) (*connect.Response[v1.PullWhitelistResponse], error) {
	return c.pullWhitelist.CallUnary(ctx, req)
}

// BanPlayer calls discopanel.v1.AdminService.BanPlayer.
func (c *adminServiceClient) BanPlayer(ctx context.Context, req *connect.Request[v1.BanPlayerRequest]) (*connect.Response[v1.BanPlayerResponse], error) {
	return c.banPlayer.CallUnary(ctx, req)
}

// UnbanPlayer calls discopanel.v1.AdminService.UnbanPlayer.
func (c *adminServiceClient) UnbanPlayer(ctx context.Context, req *connect.Request[v1.UnbanPlayerRequest]) (*connect.Response[v1.UnbanPlayerResponse], error) {
	return c.unbanPlayer.CallUnary(ctx, req)
}

// GetServerMotd calls discopanel.v1.AdminService.GetServerMotd.
func (c *adminServiceClient) GetServerMotd(ctx context.Context, req *connect.Request[v1.GetServerMotdRequest]) (*connect.Response[v1.GetServerMotdResponse], error) {
	return c.getServerMotd.CallUnary(ctx, req)
}

// UpdateServerMotd calls discopanel.v1.AdminService.UpdateServerMotd.
func (c *adminServiceClient) UpdateServerMotd(ctx context.Context, req *connect.Request[v1.UpdateServerMotdRequest]) (*connect.Response[v1.UpdateServerMotdResponse], error) {
	return c.updateServerMotd.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the discopanel.v1.AdminService service.
type AdminServiceHandler interface {
	// List whitelist entries stored in the panel
	ListWhitelistEntries(context.Context, *connect.Request[v1.ListWhitelistEntriesRequest]) (*connect.Response[v1.ListWhitelistEntriesResponse], error)
	// Add a player to the panel-side whitelist
	AddWhitelistEntry(context.Context, *connect.Request[v1.AddWhitelistEntryRequest]) (*connect.Response[v1.AddWhitelistEntryResponse], error)
	// Remove a player from the panel-side whitelist
	RemoveWhitelistEntry(context.Context, *connect.Request[v1.RemoveWhitelistEntryRequest]) (*connect.Response[v1.RemoveWhitelistEntryResponse], error)
	// Converge selected servers to the panel-side whitelist via RCON
	ApplyWhitelist(context.Context, *connect.Request[v1.ApplyWhitelistRequest]) (*connect.Response[v1.ApplyWhitelistResponse], error)
	// Read the current whitelist from a server via RCON and import it into the panel
	PullWhitelist(context.Context, *connect.Request[v1.PullWhitelistRequest]) (*connect.Response[v1.PullWhitelistResponse], error)
	// Ban a player on the selected servers via RCON
	BanPlayer(context.Context, *connect.Request[v1.BanPlayerRequest]) (*connect.Response[v1.BanPlayerResponse], error)
	// Unban a player on the selected servers via RCON
	UnbanPlayer(context.Context, *connect.Request[v1.UnbanPlayerRequest]) (*connect.Response[v1.UnbanPlayerResponse], error)
	// Read the MOTD and icon from a server's server.properties / icon.png
	GetServerMotd(context.Context, *connect.Request[v1.GetServerMotdRequest]) (*connect.Response[v1.GetServerMotdResponse], error)
	// Write the MOTD and/or icon to a server (server must be stopped to take effect on restart)
	UpdateServerMotd(context.Context, *connect.Request[v1.UpdateServerMotdRequest]) (*connect.Response[v1.UpdateServerMotdResponse], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := v1.File_discopanel_v1_admin_proto.Services().ByName("AdminService").Methods()
	adminServiceListWhitelistEntriesHandler := connect.NewUnaryHandler(
		AdminServiceListWhitelistEntriesProcedure,
		svc.ListWhitelistEntries,
		connect.WithSchema(adminServiceMethods.ByName("ListWhitelistEntries")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceAddWhitelistEntryHandler := connect.NewUnaryHandler(
		AdminServiceAddWhitelistEntryProcedure,
		svc.AddWhitelistEntry,
		connect.WithSchema(adminServiceMethods.ByName("AddWhitelistEntry")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRemoveWhitelistEntryHandler := connect.NewUnaryHandler(
		AdminServiceRemoveWhitelistEntryProcedure,
		svc.RemoveWhitelistEntry,
		connect.WithSchema(adminServiceMethods.ByName("RemoveWhitelistEntry")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceApplyWhitelistHandler := connect.NewUnaryHandler(
		AdminServiceApplyWhitelistProcedure,
		svc.ApplyWhitelist,
		connect.WithSchema(adminServiceMethods.ByName("ApplyWhitelist")),
		connect.WithHandlerOptions(opts...),
	)
	adminServicePullWhitelistHandler := connect.NewUnaryHandler(
		AdminServicePullWhitelistProcedure,
		svc.PullWhitelist,
		connect.WithSchema(adminServiceMethods.ByName("PullWhitelist")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceBanPlayerHandler := connect.NewUnaryHandler(
		AdminServiceBanPlayerProcedure,
		svc.BanPlayer,
		connect.WithSchema(adminServiceMethods.ByName("BanPlayer")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUnbanPlayerHandler := connect.NewUnaryHandler(
		AdminServiceUnbanPlayerProcedure,
		svc.UnbanPlayer,
		connect.WithSchema(adminServiceMethods.ByName("UnbanPlayer")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceGetServerMotdHandler := connect.NewUnaryHandler(
		AdminServiceGetServerMotdProcedure,
		svc.GetServerMotd,
		connect.WithSchema(adminServiceMethods.ByName("GetServerMotd")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateServerMotdHandler := connect.NewUnaryHandler(
		AdminServiceUpdateServerMotdProcedure,
		svc.UpdateServerMotd,
		connect.WithSchema(adminServiceMethods.ByName("UpdateServerMotd")),
		connect.WithHandlerOptions(opts...),
	)
	return "/discopanel.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceListWhitelistEntriesProcedure:
			adminServiceListWhitelistEntriesHandler.ServeHTTP(w, r)
		case AdminServiceAddWhitelistEntryProcedure:
			adminServiceAddWhitelistEntryHandler.ServeHTTP(w, r)
		case AdminServiceRemoveWhitelistEntryProcedure:
			adminServiceRemoveWhitelistEntryHandler.ServeHTTP(w, r)
		case AdminServiceApplyWhitelistProcedure:
			adminServiceApplyWhitelistHandler.ServeHTTP(w, r)
		case AdminServicePullWhitelistProcedure:
			adminServicePullWhitelistHandler.ServeHTTP(w, r)
		case AdminServiceBanPlayerProcedure:
			adminServiceBanPlayerHandler.ServeHTTP(w, r)
		case AdminServiceUnbanPlayerProcedure:
			adminServiceUnbanPlayerHandler.ServeHTTP(w, r)
		case AdminServiceGetServerMotdProcedure:
			adminServiceGetServerMotdHandler.ServeHTTP(w, r)
		case AdminServiceUpdateServerMotdProcedure:
			adminServiceUpdateServerMotdHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) ListWhitelistEntries(context.Context, *connect.Request[v1.ListWhitelistEntriesRequest]) (*connect.Response[v1.ListWhitelistEntriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.AdminService.ListWhitelistEntries is not implemented"))
}

func (UnimplementedAdminServiceHandler) AddWhitelistEntry(context.Context, *connect.Request[v1.AddWhitelistEntryRequest]) (*connect.Response[v1.AddWhitelistEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.AdminService.AddWhitelistEntry is not implemented"))
}

func (UnimplementedAdminServiceHandler) RemoveWhitelistEntry(context.Context, *connect.Request[v1.RemoveWhitelistEntryRequest]) (*connect.Response[v1.RemoveWhitelistEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.AdminService.RemoveWhitelistEntry is not implemented"))
}

func (UnimplementedAdminServiceHandler) ApplyWhitelist(context.Context, *connect.Request[v1.ApplyWhitelistRequest]) (*connect.Response[v1.ApplyWhitelistResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.AdminService.ApplyWhitelist is not implemented"))
}

func (UnimplementedAdminServiceHandler) PullWhitelist(context.Context, *connect.Request[v1.PullWhitelistRequest]) (*connect.Response[v1.PullWhitelistResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.AdminService.PullWhitelist is not implemented"))
}

func (UnimplementedAdminServiceHandler) BanPlayer(context.Context, *connect.Request[v1.BanPlayerRequest]) (*connect.Response[v1.BanPlayerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.AdminService.BanPlayer is not implemented"))
}

func (UnimplementedAdminServiceHandler) UnbanPlayer(context.Context, *connect.Request[v1.UnbanPlayerRequest]) (*connect.Response[v1.UnbanPlayerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.AdminService.UnbanPlayer is not implemented"))
}

func (UnimplementedAdminServiceHandler) GetServerMotd(context.Context, *connect.Request[v1.GetServerMotdRequest]) (*connect.Response[v1.GetServerMotdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.AdminService.GetServerMotd is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateServerMotd(context.Context, *connect.Request[v1.UpdateServerMotdRequest]) (*connect.Response[v1.UpdateServerMotdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.AdminService.UpdateServerMotd is not implemented"))
}
