// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: discopanel/v1/metrics.proto

package discopanelv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nickheyer/discopanel/pkg/proto/discopanel/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MetricServiceName is the fully-qualified name of the MetricService service.
	MetricServiceName = "discopanel.v1.MetricService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MetricServiceListMetricHistoryProcedure is the fully-qualified name of the MetricService's
	// ListMetricHistory RPC.
	MetricServiceListMetricHistoryProcedure = "/discopanel.v1.MetricService/ListMetricHistory"
	// MetricServiceListAlertRulesProcedure is the fully-qualified name of the MetricService's
	// ListAlertRules RPC.
	MetricServiceListAlertRulesProcedure = "/discopanel.v1.MetricService/ListAlertRules"
	// MetricServiceGetAlertRuleProcedure is the fully-qualified name of the MetricService's
	// GetAlertRule RPC.
	MetricServiceGetAlertRuleProcedure = "/discopanel.v1.MetricService/GetAlertRule"
	// MetricServiceCreateAlertRuleProcedure is the fully-qualified name of the MetricService's
	// CreateAlertRule RPC.
	MetricServiceCreateAlertRuleProcedure = "/discopanel.v1.MetricService/CreateAlertRule"
	// MetricServiceUpdateAlertRuleProcedure is the fully-qualified name of the MetricService's
	// UpdateAlertRule RPC.
	MetricServiceUpdateAlertRuleProcedure = "/discopanel.v1.MetricService/UpdateAlertRule"
	// MetricServiceDeleteAlertRuleProcedure is the fully-qualified name of the MetricService's
	// DeleteAlertRule RPC.
	MetricServiceDeleteAlertRuleProcedure = "/discopanel.v1.MetricService/DeleteAlertRule"
	// MetricServiceTestAlertRuleProcedure is the fully-qualified name of the MetricService's
	// TestAlertRule RPC.
	MetricServiceTestAlertRuleProcedure = "/discopanel.v1.MetricService/TestAlertRule"
	// MetricServiceListAlertEventsProcedure is the fully-qualified name of the MetricService's
	// ListAlertEvents RPC.
	MetricServiceListAlertEventsProcedure = "/discopanel.v1.MetricService/ListAlertEvents"
	// MetricServiceGetTrafficSummaryProcedure is the fully-qualified name of the MetricService's
	// GetTrafficSummary RPC.
	MetricServiceGetTrafficSummaryProcedure = "/discopanel.v1.MetricService/GetTrafficSummary"
)

// MetricServiceClient is a client for the discopanel.v1.MetricService service.
type MetricServiceClient interface {
	// List recorded metric samples for a server
	ListMetricHistory(context.Context, *connect.Request[v1.ListMetricHistoryRequest]) (*connect.Response[v1.ListMetricHistoryResponse], error)
	// List all alert rules
	ListAlertRules(context.Context, *connect.Request[v1.ListAlertRulesRequest]) (*connect.Response[v1.ListAlertRulesResponse], error)
	// Get a specific alert rule
	GetAlertRule(context.Context, *connect.Request[v1.GetAlertRuleRequest]) (*connect.Response[v1.GetAlertRuleResponse], error)
	// Create a new alert rule
	CreateAlertRule(context.Context, *connect.Request[v1.CreateAlertRuleRequest]) (*connect.Response[v1.CreateAlertRuleResponse], error)
	// Update an existing alert rule
	UpdateAlertRule(context.Context, *connect.Request[v1.UpdateAlertRuleRequest]) (*connect.Response[v1.UpdateAlertRuleResponse], error)
	// Delete an alert rule
	DeleteAlertRule(context.Context, *connect.Request[v1.DeleteAlertRuleRequest]) (*connect.Response[v1.DeleteAlertRuleResponse], error)
	// Evaluate a rule against current metrics without persisting state (for UI preview)
	TestAlertRule(context.Context, *connect.Request[v1.TestAlertRuleRequest]) (*connect.Response[v1.TestAlertRuleResponse], error)
	// List recent alert firing/resolution events
	ListAlertEvents(context.Context, *connect.Request[v1.ListAlertEventsRequest]) (*connect.Response[v1.ListAlertEventsResponse], error)
	// Aggregated proxy traffic per server from recorded player sessions
	GetTrafficSummary(context.Context, *connect.Request[v1.GetTrafficSummaryRequest]) (*connect.Response[v1.GetTrafficSummaryResponse], error)
}

// NewMetricServiceClient constructs a client for the discopanel.v1.MetricService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMetricServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MetricServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	metricServiceMethods := v1.File_discopanel_v1_metrics_proto.Services().ByName("MetricService").Methods()
	return &metricServiceClient{
		listMetricHistory: connect.NewClient[v1.ListMetricHistoryRequest, v1.ListMetricHistoryResponse](
			httpClient,
			baseURL+MetricServiceListMetricHistoryProcedure,
			connect.WithSchema(metricServiceMethods.ByName("ListMetricHistory")),
			connect.WithClientOptions(opts...),
		),
		listAlertRules: connect.NewClient[v1.ListAlertRulesRequest, v1.ListAlertRulesResponse](
			httpClient,
			baseURL+MetricServiceListAlertRulesProcedure,
			connect.WithSchema(metricServiceMethods.ByName("ListAlertRules")),
			connect.WithClientOptions(opts...),
		),
		getAlertRule: connect.NewClient[v1.GetAlertRuleRequest, v1.GetAlertRuleResponse](
			httpClient,
			baseURL+MetricServiceGetAlertRuleProcedure,
			connect.WithSchema(metricServiceMethods.ByName("GetAlertRule")),
			connect.WithClientOptions(opts...),
		),
		createAlertRule: connect.NewClient[v1.CreateAlertRuleRequest, v1.CreateAlertRuleResponse](
			httpClient,
			baseURL+MetricServiceCreateAlertRuleProcedure,
			connect.WithSchema(metricServiceMethods.ByName("CreateAlertRule")),
			connect.WithClientOptions(opts...),
		),
		updateAlertRule: connect.NewClient[v1.UpdateAlertRuleRequest, v1.UpdateAlertRuleResponse](
			httpClient,
			baseURL+MetricServiceUpdateAlertRuleProcedure,
			connect.WithSchema(metricServiceMethods.ByName("UpdateAlertRule")),
			connect.WithClientOptions(opts...),
		),
		deleteAlertRule: connect.NewClient[v1.DeleteAlertRuleRequest, v1.DeleteAlertRuleResponse](
			httpClient,
			baseURL+MetricServiceDeleteAlertRuleProcedure,
			connect.WithSchema(metricServiceMethods.ByName("DeleteAlertRule")),
			connect.WithClientOptions(opts...),
		),
		testAlertRule: connect.NewClient[v1.TestAlertRuleRequest, v1.TestAlertRuleResponse](
			httpClient,
			baseURL+MetricServiceTestAlertRuleProcedure,
			connect.WithSchema(metricServiceMethods.ByName("TestAlertRule")),
			connect.WithClientOptions(opts...),
		),
		listAlertEvents: connect.NewClient[v1.ListAlertEventsRequest, v1.ListAlertEventsResponse](
			httpClient,
			baseURL+MetricServiceListAlertEventsProcedure,
			connect.WithSchema(metricServiceMethods.ByName("ListAlertEvents")),
			connect.WithClientOptions(opts...),
		),
		getTrafficSummary: connect.NewClient[v1.GetTrafficSummaryRequest, v1.GetTrafficSummaryResponse](
			httpClient,
			baseURL+MetricServiceGetTrafficSummaryProcedure,
			connect.WithSchema(metricServiceMethods.ByName("GetTrafficSummary")),
			connect.WithClientOptions(opts...),
		),
	}
}

// metricServiceClient implements MetricServiceClient.
type metricServiceClient struct {
	listMetricHistory *connect.Client[v1.ListMetricHistoryRequest, v1.ListMetricHistoryResponse]
	listAlertRules    *connect.Client[v1.ListAlertRulesRequest, v1.ListAlertRulesResponse]
	getAlertRule      *connect.Client[v1.GetAlertRuleRequest, v1.GetAlertRuleResponse]
	createAlertRule   *connect.Client[v1.CreateAlertRuleRequest, v1.CreateAlertRuleResponse]
	updateAlertRule   *connect.Client[v1.UpdateAlertRuleRequest, v1.UpdateAlertRuleResponse]
	deleteAlertRule   *connect.Client[v1.DeleteAlertRuleRequest, v1.DeleteAlertRuleResponse]
	testAlertRule     *connect.Client[v1.TestAlertRuleRequest, v1.TestAlertRuleResponse]
	listAlertEvents   *connect.Client[v1.ListAlertEventsRequest, v1.ListAlertEventsResponse]
	getTrafficSummary *connect.Client[v1.GetTrafficSummaryRequest, v1.GetTrafficSummaryResponse]
}

// ListMetricHistory calls discopanel.v1.MetricService.ListMetricHistory.
func (c *metricServiceClient) ListMetricHistory(ctx context.Context, req *connect.Request[v1.ListMetricHistoryRequest]) (*connect.Response[v1.ListMetricHistoryResponse], error) {
	return c.listMetricHistory.CallUnary(ctx, req)
}

// ListAlertRules calls discopanel.v1.MetricService.ListAlertRules.
func (c *metricServiceClient) ListAlertRules(ctx context.Context, req *connect.Request[v1.ListAlertRulesRequest]) (*connect.Response[v1.ListAlertRulesResponse], error) {
	return c.listAlertRules.CallUnary(ctx, req)
}

// GetAlertRule calls discopanel.v1.MetricService.GetAlertRule.
func (c *metricServiceClient) GetAlertRule(ctx context.Context, req *connect.Request[v1.GetAlertRuleRequest]) (*connect.Response[v1.GetAlertRuleResponse], error) {
	return c.getAlertRule.CallUnary(ctx, req)
}

// CreateAlertRule calls discopanel.v1.MetricService.CreateAlertRule.
func (c *metricServiceClient) CreateAlertRule(ctx context.Context, req *connect.Request[v1.CreateAlertRuleRequest]) (*connect.Response[v1.CreateAlertRuleResponse], error) {
	return c.createAlertRule.CallUnary(ctx, req)
}

// UpdateAlertRule calls discopanel.v1.MetricService.UpdateAlertRule.
func (c *metricServiceClient) UpdateAlertRule(ctx context.Context, req *connect.Request[v1.UpdateAlertRuleRequest]) (*connect.Response[v1.UpdateAlertRuleResponse], error) {
	return c.updateAlertRule.CallUnary(ctx, req)
}

// DeleteAlertRule calls discopanel.v1.MetricService.DeleteAlertRule.
func (c *metricServiceClient) DeleteAlertRule(ctx context.Context, req *connect.Request[v1.DeleteAlertRuleRequest]) (*connect.Response[v1.DeleteAlertRuleResponse], error) {
	return c.deleteAlertRule.CallUnary(ctx, req)
}

// TestAlertRule calls discopanel.v1.MetricService.TestAlertRule.
func (c *metricServiceClient) TestAlertRule(ctx context.Context, req *connect.Request[v1.TestAlertRuleRequest]) (*connect.Response[v1.TestAlertRuleResponse], error) {
	return c.testAlertRule.CallUnary(ctx, req)
}

// ListAlertEvents calls discopanel.v1.MetricService.ListAlertEvents.
func (c *metricServiceClient) ListAlertEvents(ctx context.Context, req *connect.Request[v1.ListAlertEventsRequest]) (*connect.Response[v1.ListAlertEventsResponse], error) {
	return c.listAlertEvents.CallUnary(ctx, req)
}

// GetTrafficSummary calls discopanel.v1.MetricService.GetTrafficSummary.
func (c *metricServiceClient) GetTrafficSummary(ctx context.Context, req *connect.Request[v1.GetTrafficSummaryRequest]) (*connect.Response[v1.GetTrafficSummaryResponse], error) {
	return c.getTrafficSummary.CallUnary(ctx, req)
}

// MetricServiceHandler is an implementation of the discopanel.v1.MetricService service.
type MetricServiceHandler interface {
	// List recorded metric samples for a server
	ListMetricHistory(context.Context, *connect.Request[v1.ListMetricHistoryRequest]) (*connect.Response[v1.ListMetricHistoryResponse], error)
	// List all alert rules
	ListAlertRules(context.Context, *connect.Request[v1.ListAlertRulesRequest]) (*connect.Response[v1.ListAlertRulesResponse], error)
	// Get a specific alert rule
	GetAlertRule(context.Context, *connect.Request[v1.GetAlertRuleRequest]) (*connect.Response[v1.GetAlertRuleResponse], error)
	// Create a new alert rule
	CreateAlertRule(context.Context, *connect.Request[v1.CreateAlertRuleRequest]) (*connect.Response[v1.CreateAlertRuleResponse], error)
	// Update an existing alert rule
	UpdateAlertRule(context.Context, *connect.Request[v1.UpdateAlertRuleRequest]) (*connect.Response[v1.UpdateAlertRuleResponse], error)
	// Delete an alert rule
	DeleteAlertRule(context.Context, *connect.Request[v1.DeleteAlertRuleRequest]) (*connect.Response[v1.DeleteAlertRuleResponse], error)
	// Evaluate a rule against current metrics without persisting state (for UI preview)
	TestAlertRule(context.Context, *connect.Request[v1.TestAlertRuleRequest]) (*connect.Response[v1.TestAlertRuleResponse], error)
	// List recent alert firing/resolution events
	ListAlertEvents(context.Context, *connect.Request[v1.ListAlertEventsRequest]) (*connect.Response[v1.ListAlertEventsResponse], error)
	// Aggregated proxy traffic per server from recorded player sessions
	GetTrafficSummary(context.Context, *connect.Request[v1.GetTrafficSummaryRequest]) (*connect.Response[v1.GetTrafficSummaryResponse], error)
}

// NewMetricServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMetricServiceHandler(svc MetricServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	metricServiceMethods := v1.File_discopanel_v1_metrics_proto.Services().ByName("MetricService").Methods()
	metricServiceListMetricHistoryHandler := connect.NewUnaryHandler(
		MetricServiceListMetricHistoryProcedure,
		svc.ListMetricHistory,
		connect.WithSchema(metricServiceMethods.ByName("ListMetricHistory")),
		connect.WithHandlerOptions(opts...),
	)
	metricServiceListAlertRulesHandler := connect.NewUnaryHandler(
		MetricServiceListAlertRulesProcedure,
		svc.ListAlertRules,
		connect.WithSchema(metricServiceMethods.ByName("ListAlertRules")),
		connect.WithHandlerOptions(opts...),
	)
	metricServiceGetAlertRuleHandler := connect.NewUnaryHandler(
		MetricServiceGetAlertRuleProcedure,
		svc.GetAlertRule,
		connect.WithSchema(metricServiceMethods.ByName("GetAlertRule")),
		connect.WithHandlerOptions(opts...),
	)
	metricServiceCreateAlertRuleHandler := connect.NewUnaryHandler(
		MetricServiceCreateAlertRuleProcedure,
		svc.CreateAlertRule,
		connect.WithSchema(metricServiceMethods.ByName("CreateAlertRule")),
		connect.WithHandlerOptions(opts...),
	)
	metricServiceUpdateAlertRuleHandler := connect.NewUnaryHandler(
		MetricServiceUpdateAlertRuleProcedure,
		svc.UpdateAlertRule,
		connect.WithSchema(metricServiceMethods.ByName("UpdateAlertRule")),
		connect.WithHandlerOptions(opts...),
	)
	metricServiceDeleteAlertRuleHandler := connect.NewUnaryHandler(
		MetricServiceDeleteAlertRuleProcedure,
		svc.DeleteAlertRule,
		connect.WithSchema(metricServiceMethods.ByName("DeleteAlertRule")),
		connect.WithHandlerOptions(opts...),
	)
	metricServiceTestAlertRuleHandler := connect.NewUnaryHandler(
		MetricServiceTestAlertRuleProcedure,
		svc.TestAlertRule,
		connect.WithSchema(metricServiceMethods.ByName("TestAlertRule")),
		connect.WithHandlerOptions(opts...),
	)
	metricServiceListAlertEventsHandler := connect.NewUnaryHandler(
		MetricServiceListAlertEventsProcedure,
		svc.ListAlertEvents,
		connect.WithSchema(metricServiceMethods.ByName("ListAlertEvents")),
		connect.WithHandlerOptions(opts...),
	)
	metricServiceGetTrafficSummaryHandler := connect.NewUnaryHandler(
		MetricServiceGetTrafficSummaryProcedure,
		svc.GetTrafficSummary,
		connect.WithSchema(metricServiceMethods.ByName("GetTrafficSummary")),
		connect.WithHandlerOptions(opts...),
	)
	return "/discopanel.v1.MetricService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MetricServiceListMetricHistoryProcedure:
			metricServiceListMetricHistoryHandler.ServeHTTP(w, r)
		case MetricServiceListAlertRulesProcedure:
			metricServiceListAlertRulesHandler.ServeHTTP(w, r)
		case MetricServiceGetAlertRuleProcedure:
			metricServiceGetAlertRuleHandler.ServeHTTP(w, r)
		case MetricServiceCreateAlertRuleProcedure:
			metricServiceCreateAlertRuleHandler.ServeHTTP(w, r)
		case MetricServiceUpdateAlertRuleProcedure:
			metricServiceUpdateAlertRuleHandler.ServeHTTP(w, r)
		case MetricServiceDeleteAlertRuleProcedure:
			metricServiceDeleteAlertRuleHandler.ServeHTTP(w, r)
		case MetricServiceTestAlertRuleProcedure:
			metricServiceTestAlertRuleHandler.ServeHTTP(w, r)
		case MetricServiceListAlertEventsProcedure:
			metricServiceListAlertEventsHandler.ServeHTTP(w, r)
		case MetricServiceGetTrafficSummaryProcedure:
			metricServiceGetTrafficSummaryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMetricServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMetricServiceHandler struct{}

func (UnimplementedMetricServiceHandler) ListMetricHistory(context.Context, *connect.Request[v1.ListMetricHistoryRequest]) (*connect.Response[v1.ListMetricHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.MetricService.ListMetricHistory is not implemented"))
}

func (UnimplementedMetricServiceHandler) ListAlertRules(context.Context, *connect.Request[v1.ListAlertRulesRequest]) (*connect.Response[v1.ListAlertRulesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.MetricService.ListAlertRules is not implemented"))
}

func (UnimplementedMetricServiceHandler) GetAlertRule(context.Context, *connect.Request[v1.GetAlertRuleRequest]) (*connect.Response[v1.GetAlertRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.MetricService.GetAlertRule is not implemented"))
}

func (UnimplementedMetricServiceHandler) CreateAlertRule(context.Context, *connect.Request[v1.CreateAlertRuleRequest]) (*connect.Response[v1.CreateAlertRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.MetricService.CreateAlertRule is not implemented"))
}

func (UnimplementedMetricServiceHandler) UpdateAlertRule(context.Context, *connect.Request[v1.UpdateAlertRuleRequest]) (*connect.Response[v1.UpdateAlertRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.MetricService.UpdateAlertRule is not implemented"))
}

func (UnimplementedMetricServiceHandler) DeleteAlertRule(context.Context, *connect.Request[v1.DeleteAlertRuleRequest]) (*connect.Response[v1.DeleteAlertRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.MetricService.DeleteAlertRule is not implemented"))
}

func (UnimplementedMetricServiceHandler) TestAlertRule(context.Context, *connect.Request[v1.TestAlertRuleRequest]) (*connect.Response[v1.TestAlertRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.MetricService.TestAlertRule is not implemented"))
}

func (UnimplementedMetricServiceHandler) ListAlertEvents(context.Context, *connect.Request[v1.ListAlertEventsRequest]) (*connect.Response[v1.ListAlertEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.MetricService.ListAlertEvents is not implemented"))
}

func (UnimplementedMetricServiceHandler) GetTrafficSummary(context.Context, *connect.Request[v1.GetTrafficSummaryRequest]) (*connect.Response[v1.GetTrafficSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.MetricService.GetTrafficSummary is not implemented"))
}
