// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: discopanel/v1/modpack_update.proto

package discopanelv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nickheyer/discopanel/pkg/proto/discopanel/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ModpackUpdateServiceName is the fully-qualified name of the ModpackUpdateService service.
	ModpackUpdateServiceName = "discopanel.v1.ModpackUpdateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ModpackUpdateServiceCheckModpackUpdateProcedure is the fully-qualified name of the
	// ModpackUpdateService's CheckModpackUpdate RPC.
	ModpackUpdateServiceCheckModpackUpdateProcedure = "/discopanel.v1.ModpackUpdateService/CheckModpackUpdate"
	// ModpackUpdateServiceUpdateServerModpackProcedure is the fully-qualified name of the
	// ModpackUpdateService's UpdateServerModpack RPC.
	ModpackUpdateServiceUpdateServerModpackProcedure = "/discopanel.v1.ModpackUpdateService/UpdateServerModpack"
	// ModpackUpdateServiceListModpackVersionsProcedure is the fully-qualified name of the
	// ModpackUpdateService's ListModpackVersions RPC.
	ModpackUpdateServiceListModpackVersionsProcedure = "/discopanel.v1.ModpackUpdateService/ListModpackVersions"
	// ModpackUpdateServiceRollbackModpackUpdateProcedure is the fully-qualified name of the
	// ModpackUpdateService's RollbackModpackUpdate RPC.
	ModpackUpdateServiceRollbackModpackUpdateProcedure = "/discopanel.v1.ModpackUpdateService/RollbackModpackUpdate"
	// ModpackUpdateServiceGetModpackUpdateSettingsProcedure is the fully-qualified name of the
	// ModpackUpdateService's GetModpackUpdateSettings RPC.
	ModpackUpdateServiceGetModpackUpdateSettingsProcedure = "/discopanel.v1.ModpackUpdateService/GetModpackUpdateSettings"
	// ModpackUpdateServiceSetModpackUpdateSettingsProcedure is the fully-qualified name of the
	// ModpackUpdateService's SetModpackUpdateSettings RPC.
	ModpackUpdateServiceSetModpackUpdateSettingsProcedure = "/discopanel.v1.ModpackUpdateService/SetModpackUpdateSettings"
)

// ModpackUpdateServiceClient is a client for the discopanel.v1.ModpackUpdateService service.
type ModpackUpdateServiceClient interface {
	// Check whether a newer version of a server's modpack is available
	CheckModpackUpdate(context.Context, *connect.Request[v1.CheckModpackUpdateRequest]) (*connect.Response[v1.CheckModpackUpdateResponse], error)
	// Update a server's modpack to a target version (world preserved, optional pre-update backup)
	UpdateServerModpack(context.Context, *connect.Request[v1.UpdateServerModpackRequest]) (*connect.Response[v1.UpdateServerModpackResponse], error)
	// List versions available for a server's modpack
	ListModpackVersions(context.Context, *connect.Request[v1.ListModpackVersionsRequest]) (*connect.Response[v1.ListModpackVersionsResponse], error)
	// Restore the pre-update backup created by the last update (server must be stopped)
	RollbackModpackUpdate(context.Context, *connect.Request[v1.RollbackModpackUpdateRequest]) (*connect.Response[v1.RollbackModpackUpdateResponse], error)
	// Get the scheduled-update settings for a server
	GetModpackUpdateSettings(context.Context, *connect.Request[v1.GetModpackUpdateSettingsRequest]) (*connect.Response[v1.GetModpackUpdateSettingsResponse], error)
	// Set the scheduled-update settings for a server
	SetModpackUpdateSettings(context.Context, *connect.Request[v1.SetModpackUpdateSettingsRequest]) (*connect.Response[v1.SetModpackUpdateSettingsResponse], error)
}

// NewModpackUpdateServiceClient constructs a client for the discopanel.v1.ModpackUpdateService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewModpackUpdateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ModpackUpdateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	modpackUpdateServiceMethods := v1.File_discopanel_v1_modpack_update_proto.Services().ByName("ModpackUpdateService").Methods()
	return &modpackUpdateServiceClient{
		checkModpackUpdate: connect.NewClient[v1.CheckModpackUpdateRequest, v1.CheckModpackUpdateResponse](
			httpClient,
			baseURL+ModpackUpdateServiceCheckModpackUpdateProcedure,
			connect.WithSchema(modpackUpdateServiceMethods.ByName("CheckModpackUpdate")),
			connect.WithClientOptions(opts...),
		),
		updateServerModpack: connect.NewClient[v1.UpdateServerModpackRequest, v1.UpdateServerModpackResponse](
			httpClient,
			baseURL+ModpackUpdateServiceUpdateServerModpackProcedure,
			connect.WithSchema(modpackUpdateServiceMethods.ByName("UpdateServerModpack")),
			connect.WithClientOptions(opts...),
		),
		listModpackVersions: connect.NewClient[v1.ListModpackVersionsRequest, v1.ListModpackVersionsResponse](
			httpClient,
			baseURL+ModpackUpdateServiceListModpackVersionsProcedure,
			connect.WithSchema(modpackUpdateServiceMethods.ByName("ListModpackVersions")),
			connect.WithClientOptions(opts...),
		),
		rollbackModpackUpdate: connect.NewClient[v1.RollbackModpackUpdateRequest, v1.RollbackModpackUpdateResponse](
			httpClient,
			baseURL+ModpackUpdateServiceRollbackModpackUpdateProcedure,
			connect.WithSchema(modpackUpdateServiceMethods.ByName("RollbackModpackUpdate")),
			connect.WithClientOptions(opts...),
		),
		getModpackUpdateSettings: connect.NewClient[v1.GetModpackUpdateSettingsRequest, v1.GetModpackUpdateSettingsResponse](
			httpClient,
			baseURL+ModpackUpdateServiceGetModpackUpdateSettingsProcedure,
			connect.WithSchema(modpackUpdateServiceMethods.ByName("GetModpackUpdateSettings")),
			connect.WithClientOptions(opts...),
		),
		setModpackUpdateSettings: connect.NewClient[v1.SetModpackUpdateSettingsRequest, v1.SetModpackUpdateSettingsResponse](
			httpClient,
			baseURL+ModpackUpdateServiceSetModpackUpdateSettingsProcedure,
			connect.WithSchema(modpackUpdateServiceMethods.ByName("SetModpackUpdateSettings")),
			connect.WithClientOptions(opts...),
		),
	}
}

// modpackUpdateServiceClient implements ModpackUpdateServiceClient.
type modpackUpdateServiceClient struct {
	checkModpackUpdate       *connect.Client[v1.CheckModpackUpdateRequest, v1.CheckModpackUpdateResponse]
	updateServerModpack      *connect.Client[v1.UpdateServerModpackRequest, v1.UpdateServerModpackResponse]
	listModpackVersions      *connect.Client[v1.ListModpackVersionsRequest, v1.ListModpackVersionsResponse]
	rollbackModpackUpdate    *connect.Client[v1.RollbackModpackUpdateRequest, v1.RollbackModpackUpdateResponse]
	getModpackUpdateSettings *connect.Client[v1.GetModpackUpdateSettingsRequest, v1.GetModpackUpdateSettingsResponse]
	setModpackUpdateSettings *connect.Client[v1.SetModpackUpdateSettingsRequest, v1.SetModpackUpdateSettingsResponse]
}

// CheckModpackUpdate calls discopanel.v1.ModpackUpdateService.CheckModpackUpdate.
func (c *modpackUpdateServiceClient) CheckModpackUpdate(ctx context.Context, req *connect.Request[v1.CheckModpackUpdateRequest]) (*connect.Response[v1.CheckModpackUpdateResponse], error) {
	return c.checkModpackUpdate.CallUnary(ctx, req)
}

// UpdateServerModpack calls discopanel.v1.ModpackUpdateService.UpdateServerModpack.
func (c *modpackUpdateServiceClient) UpdateServerModpack(ctx context.Context, req *connect.Request[v1.UpdateServerModpackRequest]) (*connect.Response[v1.UpdateServerModpackResponse], error) {
	return c.updateServerModpack.CallUnary(ctx, req)
}

// ListModpackVersions calls discopanel.v1.ModpackUpdateService.ListModpackVersions.
func (c *modpackUpdateServiceClient) ListModpackVersions(ctx context.Context, req *connect.Request[v1.ListModpackVersionsRequest]) (*connect.Response[v1.ListModpackVersionsResponse], error) {
	return c.listModpackVersions.CallUnary(ctx, req)
}

// RollbackModpackUpdate calls discopanel.v1.ModpackUpdateService.RollbackModpackUpdate.
func (c *modpackUpdateServiceClient) RollbackModpackUpdate(ctx context.Context, req *connect.Request[v1.RollbackModpackUpdateRequest]) (*connect.Response[v1.RollbackModpackUpdateResponse], error) {
	return c.rollbackModpackUpdate.CallUnary(ctx, req)
}

// GetModpackUpdateSettings calls discopanel.v1.ModpackUpdateService.GetModpackUpdateSettings.
func (c *modpackUpdateServiceClient) GetModpackUpdateSettings(ctx context.Context, req *connect.Request[v1.GetModpackUpdateSettingsRequest]) (*connect.Response[v1.GetModpackUpdateSettingsResponse], error) {
	return c.getModpackUpdateSettings.CallUnary(ctx, req)
}

// SetModpackUpdateSettings calls discopanel.v1.ModpackUpdateService.SetModpackUpdateSettings.
func (c *modpackUpdateServiceClient) SetModpackUpdateSettings(ctx context.Context, req *connect.Request[v1.SetModpackUpdateSettingsRequest]) (*connect.Response[v1.SetModpackUpdateSettingsResponse], error) {
	return c.setModpackUpdateSettings.CallUnary(ctx, req)
}

// ModpackUpdateServiceHandler is an implementation of the discopanel.v1.ModpackUpdateService
// service.
type ModpackUpdateServiceHandler interface {
	// Check whether a newer version of a server's modpack is available
	CheckModpackUpdate(context.Context, *connect.Request[v1.CheckModpackUpdateRequest]) (*connect.Response[v1.CheckModpackUpdateResponse], error)
	// Update a server's modpack to a target version (world preserved, optional pre-update backup)
	UpdateServerModpack(context.Context, *connect.Request[v1.UpdateServerModpackRequest]) (*connect.Response[v1.UpdateServerModpackResponse], error)
	// List versions available for a server's modpack
	ListModpackVersions(context.Context, *connect.Request[v1.ListModpackVersionsRequest]) (*connect.Response[v1.ListModpackVersionsResponse], error)
	// Restore the pre-update backup created by the last update (server must be stopped)
	RollbackModpackUpdate(context.Context, *connect.Request[v1.RollbackModpackUpdateRequest]) (*connect.Response[v1.RollbackModpackUpdateResponse], error)
	// Get the scheduled-update settings for a server
	GetModpackUpdateSettings(context.Context, *connect.Request[v1.GetModpackUpdateSettingsRequest]) (*connect.Response[v1.GetModpackUpdateSettingsResponse], error)
	// Set the scheduled-update settings for a server
	SetModpackUpdateSettings(context.Context, *connect.Request[v1.SetModpackUpdateSettingsRequest]) (*connect.Response[v1.SetModpackUpdateSettingsResponse], error)
}

// NewModpackUpdateServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewModpackUpdateServiceHandler(svc ModpackUpdateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	modpackUpdateServiceMethods := v1.File_discopanel_v1_modpack_update_proto.Services().ByName("ModpackUpdateService").Methods()
	modpackUpdateServiceCheckModpackUpdateHandler := connect.NewUnaryHandler(
		ModpackUpdateServiceCheckModpackUpdateProcedure,
		svc.CheckModpackUpdate,
		connect.WithSchema(modpackUpdateServiceMethods.ByName("CheckModpackUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	modpackUpdateServiceUpdateServerModpackHandler := connect.NewUnaryHandler(
		ModpackUpdateServiceUpdateServerModpackProcedure,
		svc.UpdateServerModpack,
		connect.WithSchema(modpackUpdateServiceMethods.ByName("UpdateServerModpack")),
		connect.WithHandlerOptions(opts...),
	)
	modpackUpdateServiceListModpackVersionsHandler := connect.NewUnaryHandler(
		ModpackUpdateServiceListModpackVersionsProcedure,
		svc.ListModpackVersions,
		connect.WithSchema(modpackUpdateServiceMethods.ByName("ListModpackVersions")),
		connect.WithHandlerOptions(opts...),
	)
	modpackUpdateServiceRollbackModpackUpdateHandler := connect.NewUnaryHandler(
		ModpackUpdateServiceRollbackModpackUpdateProcedure,
		svc.RollbackModpackUpdate,
		connect.WithSchema(modpackUpdateServiceMethods.ByName("RollbackModpackUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	modpackUpdateServiceGetModpackUpdateSettingsHandler := connect.NewUnaryHandler(
		ModpackUpdateServiceGetModpackUpdateSettingsProcedure,
		svc.GetModpackUpdateSettings,
		connect.WithSchema(modpackUpdateServiceMethods.ByName("GetModpackUpdateSettings")),
		connect.WithHandlerOptions(opts...),
	)
	modpackUpdateServiceSetModpackUpdateSettingsHandler := connect.NewUnaryHandler(
		ModpackUpdateServiceSetModpackUpdateSettingsProcedure,
		svc.SetModpackUpdateSettings,
		connect.WithSchema(modpackUpdateServiceMethods.ByName("SetModpackUpdateSettings")),
		connect.WithHandlerOptions(opts...),
	)
	return "/discopanel.v1.ModpackUpdateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ModpackUpdateServiceCheckModpackUpdateProcedure:
			modpackUpdateServiceCheckModpackUpdateHandler.ServeHTTP(w, r)
		case ModpackUpdateServiceUpdateServerModpackProcedure:
			modpackUpdateServiceUpdateServerModpackHandler.ServeHTTP(w, r)
		case ModpackUpdateServiceListModpackVersionsProcedure:
			modpackUpdateServiceListModpackVersionsHandler.ServeHTTP(w, r)
		case ModpackUpdateServiceRollbackModpackUpdateProcedure:
			modpackUpdateServiceRollbackModpackUpdateHandler.ServeHTTP(w, r)
		case ModpackUpdateServiceGetModpackUpdateSettingsProcedure:
			modpackUpdateServiceGetModpackUpdateSettingsHandler.ServeHTTP(w, r)
		case ModpackUpdateServiceSetModpackUpdateSettingsProcedure:
			modpackUpdateServiceSetModpackUpdateSettingsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedModpackUpdateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedModpackUpdateServiceHandler struct{}

func (UnimplementedModpackUpdateServiceHandler) CheckModpackUpdate(context.Context, *connect.Request[v1.CheckModpackUpdateRequest]) (*connect.Response[v1.CheckModpackUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ModpackUpdateService.CheckModpackUpdate is not implemented"))
}

func (UnimplementedModpackUpdateServiceHandler) UpdateServerModpack(context.Context, *connect.Request[v1.UpdateServerModpackRequest]) (*connect.Response[v1.UpdateServerModpackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ModpackUpdateService.UpdateServerModpack is not implemented"))
}

func (UnimplementedModpackUpdateServiceHandler) ListModpackVersions(context.Context, *connect.Request[v1.ListModpackVersionsRequest]) (*connect.Response[v1.ListModpackVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ModpackUpdateService.ListModpackVersions is not implemented"))
}

func (UnimplementedModpackUpdateServiceHandler) RollbackModpackUpdate(context.Context, *connect.Request[v1.RollbackModpackUpdateRequest]) (*connect.Response[v1.RollbackModpackUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ModpackUpdateService.RollbackModpackUpdate is not implemented"))
}

func (UnimplementedModpackUpdateServiceHandler) GetModpackUpdateSettings(context.Context, *connect.Request[v1.GetModpackUpdateSettingsRequest]) (*connect.Response[v1.GetModpackUpdateSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ModpackUpdateService.GetModpackUpdateSettings is not implemented"))
}

func (UnimplementedModpackUpdateServiceHandler) SetModpackUpdateSettings(context.Context, *connect.Request[v1.SetModpackUpdateSettingsRequest]) (*connect.Response[v1.SetModpackUpdateSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ModpackUpdateService.SetModpackUpdateSettings is not implemented"))
}
