// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: discopanel/v1/template.proto

package discopanelv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nickheyer/discopanel/pkg/proto/discopanel/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TemplateServiceName is the fully-qualified name of the TemplateService service.
	TemplateServiceName = "discopanel.v1.TemplateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TemplateServiceListServerTemplatesProcedure is the fully-qualified name of the TemplateService's
	// ListServerTemplates RPC.
	TemplateServiceListServerTemplatesProcedure = "/discopanel.v1.TemplateService/ListServerTemplates"
	// TemplateServiceCreateServerTemplateProcedure is the fully-qualified name of the TemplateService's
	// CreateServerTemplate RPC.
	TemplateServiceCreateServerTemplateProcedure = "/discopanel.v1.TemplateService/CreateServerTemplate"
	// TemplateServiceUpdateServerTemplateProcedure is the fully-qualified name of the TemplateService's
	// UpdateServerTemplate RPC.
	TemplateServiceUpdateServerTemplateProcedure = "/discopanel.v1.TemplateService/UpdateServerTemplate"
	// TemplateServiceDeleteServerTemplateProcedure is the fully-qualified name of the TemplateService's
	// DeleteServerTemplate RPC.
	TemplateServiceDeleteServerTemplateProcedure = "/discopanel.v1.TemplateService/DeleteServerTemplate"
	// TemplateServiceDeployServerTemplateProcedure is the fully-qualified name of the TemplateService's
	// DeployServerTemplate RPC.
	TemplateServiceDeployServerTemplateProcedure = "/discopanel.v1.TemplateService/DeployServerTemplate"
)

// TemplateServiceClient is a client for the discopanel.v1.TemplateService service.
type TemplateServiceClient interface {
	// List all server templates
	ListServerTemplates(context.Context, *connect.Request[v1.ListServerTemplatesRequest]) (*connect.Response[v1.ListServerTemplatesResponse], error)
	// Capture a template from an existing server (config + optional mods)
	CreateServerTemplate(context.Context, *connect.Request[v1.CreateServerTemplateRequest]) (*connect.Response[v1.CreateServerTemplateResponse], error)
	// Update a template's metadata
	UpdateServerTemplate(context.Context, *connect.Request[v1.UpdateServerTemplateRequest]) (*connect.Response[v1.UpdateServerTemplateResponse], error)
	// Delete a template (and its captured mods)
	DeleteServerTemplate(context.Context, *connect.Request[v1.DeleteServerTemplateRequest]) (*connect.Response[v1.DeleteServerTemplateResponse], error)
	// Create a new server from a template
	DeployServerTemplate(context.Context, *connect.Request[v1.DeployServerTemplateRequest]) (*connect.Response[v1.DeployServerTemplateResponse], error)
}

// NewTemplateServiceClient constructs a client for the discopanel.v1.TemplateService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTemplateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TemplateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	templateServiceMethods := v1.File_discopanel_v1_template_proto.Services().ByName("TemplateService").Methods()
	return &templateServiceClient{
		listServerTemplates: connect.NewClient[v1.ListServerTemplatesRequest, v1.ListServerTemplatesResponse](
			httpClient,
			baseURL+TemplateServiceListServerTemplatesProcedure,
			connect.WithSchema(templateServiceMethods.ByName("ListServerTemplates")),
			connect.WithClientOptions(opts...),
		),
		createServerTemplate: connect.NewClient[v1.CreateServerTemplateRequest, v1.CreateServerTemplateResponse](
			httpClient,
			baseURL+TemplateServiceCreateServerTemplateProcedure,
			connect.WithSchema(templateServiceMethods.ByName("CreateServerTemplate")),
			connect.WithClientOptions(opts...),
		),
		updateServerTemplate: connect.NewClient[v1.UpdateServerTemplateRequest, v1.UpdateServerTemplateResponse](
			httpClient,
			baseURL+TemplateServiceUpdateServerTemplateProcedure,
			connect.WithSchema(templateServiceMethods.ByName("UpdateServerTemplate")),
			connect.WithClientOptions(opts...),
		),
		deleteServerTemplate: connect.NewClient[v1.DeleteServerTemplateRequest, v1.DeleteServerTemplateResponse](
			httpClient,
			baseURL+TemplateServiceDeleteServerTemplateProcedure,
			connect.WithSchema(templateServiceMethods.ByName("DeleteServerTemplate")),
			connect.WithClientOptions(opts...),
		),
		deployServerTemplate: connect.NewClient[v1.DeployServerTemplateRequest, v1.DeployServerTemplateResponse](
			httpClient,
			baseURL+TemplateServiceDeployServerTemplateProcedure,
			connect.WithSchema(templateServiceMethods.ByName("DeployServerTemplate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// templateServiceClient implements TemplateServiceClient.
type templateServiceClient struct {
	listServerTemplates  *connect.Client[v1.ListServerTemplatesRequest, v1.ListServerTemplatesResponse]
	createServerTemplate *connect.Client[v1.CreateServerTemplateRequest, v1.CreateServerTemplateResponse]
	updateServerTemplate *connect.Client[v1.UpdateServerTemplateRequest, v1.UpdateServerTemplateResponse]
	deleteServerTemplate *connect.Client[v1.DeleteServerTemplateRequest, v1.DeleteServerTemplateResponse]
	deployServerTemplate *connect.Client[v1.DeployServerTemplateRequest, v1.DeployServerTemplateResponse]
}

// ListServerTemplates calls discopanel.v1.TemplateService.ListServerTemplates.
func (c *templateServiceClient) ListServerTemplates(ctx context.Context, req *connect.Request[v1.ListServerTemplatesRequest]) (*connect.Response[v1.ListServerTemplatesResponse], error) {
	return c.listServerTemplates.CallUnary(ctx, req)
}

// CreateServerTemplate calls discopanel.v1.TemplateService.CreateServerTemplate.
func (c *templateServiceClient) CreateServerTemplate(ctx context.Context, req *connect.Request[v1.CreateServerTemplateRequest]) (*connect.Response[v1.CreateServerTemplateResponse], error) {
	return c.createServerTemplate.CallUnary(ctx, req)
}

// UpdateServerTemplate calls discopanel.v1.TemplateService.UpdateServerTemplate.
func (c *templateServiceClient) UpdateServerTemplate(ctx context.Context, req *connect.Request[v1.UpdateServerTemplateRequest]) (*connect.Response[v1.UpdateServerTemplateResponse], error) {
	return c.updateServerTemplate.CallUnary(ctx, req)
}

// DeleteServerTemplate calls discopanel.v1.TemplateService.DeleteServerTemplate.
func (c *templateServiceClient) DeleteServerTemplate(ctx context.Context, req *connect.Request[v1.DeleteServerTemplateRequest]) (*connect.Response[v1.DeleteServerTemplateResponse], error) {
	return c.deleteServerTemplate.CallUnary(ctx, req)
}

// DeployServerTemplate calls discopanel.v1.TemplateService.DeployServerTemplate.
func (c *templateServiceClient) DeployServerTemplate(ctx context.Context, req *connect.Request[v1.DeployServerTemplateRequest]) (*connect.Response[v1.DeployServerTemplateResponse], error) {
	return c.deployServerTemplate.CallUnary(ctx, req)
}

// TemplateServiceHandler is an implementation of the discopanel.v1.TemplateService service.
type TemplateServiceHandler interface {
	// List all server templates
	ListServerTemplates(context.Context, *connect.Request[v1.ListServerTemplatesRequest]) (*connect.Response[v1.ListServerTemplatesResponse], error)
	// Capture a template from an existing server (config + optional mods)
	CreateServerTemplate(context.Context, *connect.Request[v1.CreateServerTemplateRequest]) (*connect.Response[v1.CreateServerTemplateResponse], error)
	// Update a template's metadata
	UpdateServerTemplate(context.Context, *connect.Request[v1.UpdateServerTemplateRequest]) (*connect.Response[v1.UpdateServerTemplateResponse], error)
	// Delete a template (and its captured mods)
	DeleteServerTemplate(context.Context, *connect.Request[v1.DeleteServerTemplateRequest]) (*connect.Response[v1.DeleteServerTemplateResponse], error)
	// Create a new server from a template
	DeployServerTemplate(context.Context, *connect.Request[v1.DeployServerTemplateRequest]) (*connect.Response[v1.DeployServerTemplateResponse], error)
}

// NewTemplateServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTemplateServiceHandler(svc TemplateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	templateServiceMethods := v1.File_discopanel_v1_template_proto.Services().ByName("TemplateService").Methods()
	templateServiceListServerTemplatesHandler := connect.NewUnaryHandler(
		TemplateServiceListServerTemplatesProcedure,
		svc.ListServerTemplates,
		connect.WithSchema(templateServiceMethods.ByName("ListServerTemplates")),
		connect.WithHandlerOptions(opts...),
	)
	templateServiceCreateServerTemplateHandler := connect.NewUnaryHandler(
		TemplateServiceCreateServerTemplateProcedure,
		svc.CreateServerTemplate,
		connect.WithSchema(templateServiceMethods.ByName("CreateServerTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	templateServiceUpdateServerTemplateHandler := connect.NewUnaryHandler(
		TemplateServiceUpdateServerTemplateProcedure,
		svc.UpdateServerTemplate,
		connect.WithSchema(templateServiceMethods.ByName("UpdateServerTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	templateServiceDeleteServerTemplateHandler := connect.NewUnaryHandler(
		TemplateServiceDeleteServerTemplateProcedure,
		svc.DeleteServerTemplate,
		connect.WithSchema(templateServiceMethods.ByName("DeleteServerTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	templateServiceDeployServerTemplateHandler := connect.NewUnaryHandler(
		TemplateServiceDeployServerTemplateProcedure,
		svc.DeployServerTemplate,
		connect.WithSchema(templateServiceMethods.ByName("DeployServerTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/discopanel.v1.TemplateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TemplateServiceListServerTemplatesProcedure:
			templateServiceListServerTemplatesHandler.ServeHTTP(w, r)
		case TemplateServiceCreateServerTemplateProcedure:
			templateServiceCreateServerTemplateHandler.ServeHTTP(w, r)
		case TemplateServiceUpdateServerTemplateProcedure:
			templateServiceUpdateServerTemplateHandler.ServeHTTP(w, r)
		case TemplateServiceDeleteServerTemplateProcedure:
			templateServiceDeleteServerTemplateHandler.ServeHTTP(w, r)
		case TemplateServiceDeployServerTemplateProcedure:
			templateServiceDeployServerTemplateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTemplateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTemplateServiceHandler struct{}

func (UnimplementedTemplateServiceHandler) ListServerTemplates(context.Context, *connect.Request[v1.ListServerTemplatesRequest]) (*connect.Response[v1.ListServerTemplatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.TemplateService.ListServerTemplates is not implemented"))
}

func (UnimplementedTemplateServiceHandler) CreateServerTemplate(context.Context, *connect.Request[v1.CreateServerTemplateRequest]) (*connect.Response[v1.CreateServerTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.TemplateService.CreateServerTemplate is not implemented"))
}

func (UnimplementedTemplateServiceHandler) UpdateServerTemplate(context.Context, *connect.Request[v1.UpdateServerTemplateRequest]) (*connect.Response[v1.UpdateServerTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.TemplateService.UpdateServerTemplate is not implemented"))
}

func (UnimplementedTemplateServiceHandler) DeleteServerTemplate(context.Context, *connect.Request[v1.DeleteServerTemplateRequest]) (*connect.Response[v1.DeleteServerTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.TemplateService.DeleteServerTemplate is not implemented"))
}

func (UnimplementedTemplateServiceHandler) DeployServerTemplate(context.Context, *connect.Request[v1.DeployServerTemplateRequest]) (*connect.Response[v1.DeployServerTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.TemplateService.DeployServerTemplate is not implemented"))
}
