// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: discopanel/v1/admin.proto

package discopanelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A whitelisted player (panel-side desired state)
type WhitelistEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistEntry) Reset() {
	*x = WhitelistEntry{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistEntry) ProtoMessage() {}

func (x *WhitelistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistEntry.ProtoReflect.Descriptor instead.
func (*WhitelistEntry) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *WhitelistEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WhitelistEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WhitelistEntry) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *WhitelistEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Outcome of applying whitelist/ban commands to one server
type ServerOpResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Added         []string               `protobuf:"bytes,5,rep,name=added,proto3" json:"added,omitempty"`     // Names added on this server (whitelist apply)
	Removed       []string               `protobuf:"bytes,6,rep,name=removed,proto3" json:"removed,omitempty"` // Names removed on this server (whitelist apply)
	Current       []string               `protobuf:"bytes,7,rep,name=current,proto3" json:"current,omitempty"` // Final whitelist on this server (empty for ban ops)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerOpResult) Reset() {
	*x = ServerOpResult{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerOpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerOpResult) ProtoMessage() {}

func (x *ServerOpResult) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerOpResult.ProtoReflect.Descriptor instead.
func (*ServerOpResult) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ServerOpResult) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerOpResult) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerOpResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerOpResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerOpResult) GetAdded() []string {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *ServerOpResult) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *ServerOpResult) GetCurrent() []string {
	if x != nil {
		return x.Current
	}
	return nil
}

// List whitelist entries request
type ListWhitelistEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"` // Optional name substring filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWhitelistEntriesRequest) Reset() {
	*x = ListWhitelistEntriesRequest{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWhitelistEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWhitelistEntriesRequest) ProtoMessage() {}

func (x *ListWhitelistEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWhitelistEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListWhitelistEntriesRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListWhitelistEntriesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

// List whitelist entries response
type ListWhitelistEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*WhitelistEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWhitelistEntriesResponse) Reset() {
	*x = ListWhitelistEntriesResponse{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWhitelistEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWhitelistEntriesResponse) ProtoMessage() {}

func (x *ListWhitelistEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWhitelistEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListWhitelistEntriesResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListWhitelistEntriesResponse) GetEntries() []*WhitelistEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Add whitelist entry request
type AddWhitelistEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWhitelistEntryRequest) Reset() {
	*x = AddWhitelistEntryRequest{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWhitelistEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWhitelistEntryRequest) ProtoMessage() {}

func (x *AddWhitelistEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWhitelistEntryRequest.ProtoReflect.Descriptor instead.
func (*AddWhitelistEntryRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AddWhitelistEntryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddWhitelistEntryRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// Add whitelist entry response
type AddWhitelistEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *WhitelistEntry        `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWhitelistEntryResponse) Reset() {
	*x = AddWhitelistEntryResponse{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWhitelistEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWhitelistEntryResponse) ProtoMessage() {}

func (x *AddWhitelistEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWhitelistEntryResponse.ProtoReflect.Descriptor instead.
func (*AddWhitelistEntryResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *AddWhitelistEntryResponse) GetEntry() *WhitelistEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// Remove whitelist entry request
type RemoveWhitelistEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWhitelistEntryRequest) Reset() {
	*x = RemoveWhitelistEntryRequest{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWhitelistEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWhitelistEntryRequest) ProtoMessage() {}

func (x *RemoveWhitelistEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWhitelistEntryRequest.ProtoReflect.Descriptor instead.
func (*RemoveWhitelistEntryRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveWhitelistEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Remove whitelist entry response
type RemoveWhitelistEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWhitelistEntryResponse) Reset() {
	*x = RemoveWhitelistEntryResponse{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWhitelistEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWhitelistEntryResponse) ProtoMessage() {}

func (x *RemoveWhitelistEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWhitelistEntryResponse.ProtoReflect.Descriptor instead.
func (*RemoveWhitelistEntryResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{7}
}

// Apply whitelist request
type ApplyWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerIds     []string               `protobuf:"bytes,1,rep,name=server_ids,json=serverIds,proto3" json:"server_ids,omitempty"` // Empty = all servers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWhitelistRequest) Reset() {
	*x = ApplyWhitelistRequest{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWhitelistRequest) ProtoMessage() {}

func (x *ApplyWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWhitelistRequest.ProtoReflect.Descriptor instead.
func (*ApplyWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyWhitelistRequest) GetServerIds() []string {
	if x != nil {
		return x.ServerIds
	}
	return nil
}

// Apply whitelist response
type ApplyWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ServerOpResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWhitelistResponse) Reset() {
	*x = ApplyWhitelistResponse{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWhitelistResponse) ProtoMessage() {}

func (x *ApplyWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWhitelistResponse.ProtoReflect.Descriptor instead.
func (*ApplyWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyWhitelistResponse) GetResults() []*ServerOpResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// Pull whitelist request
type PullWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullWhitelistRequest) Reset() {
	*x = PullWhitelistRequest{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullWhitelistRequest) ProtoMessage() {}

func (x *PullWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullWhitelistRequest.ProtoReflect.Descriptor instead.
func (*PullWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *PullWhitelistRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// Pull whitelist response
type PullWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imported      []string               `protobuf:"bytes,2,rep,name=imported,proto3" json:"imported,omitempty"` // Names now in the panel whitelist
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullWhitelistResponse) Reset() {
	*x = PullWhitelistResponse{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullWhitelistResponse) ProtoMessage() {}

func (x *PullWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullWhitelistResponse.ProtoReflect.Descriptor instead.
func (*PullWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *PullWhitelistResponse) GetImported() []string {
	if x != nil {
		return x.Imported
	}
	return nil
}

// Ban player request
type BanPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerIds     []string               `protobuf:"bytes,1,rep,name=server_ids,json=serverIds,proto3" json:"server_ids,omitempty"` // Empty = all servers
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPlayerRequest) Reset() {
	*x = BanPlayerRequest{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPlayerRequest) ProtoMessage() {}

func (x *BanPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPlayerRequest.ProtoReflect.Descriptor instead.
func (*BanPlayerRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *BanPlayerRequest) GetServerIds() []string {
	if x != nil {
		return x.ServerIds
	}
	return nil
}

func (x *BanPlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BanPlayerRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Ban player response
type BanPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ServerOpResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPlayerResponse) Reset() {
	*x = BanPlayerResponse{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPlayerResponse) ProtoMessage() {}

func (x *BanPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPlayerResponse.ProtoReflect.Descriptor instead.
func (*BanPlayerResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *BanPlayerResponse) GetResults() []*ServerOpResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// Unban player request
type UnbanPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerIds     []string               `protobuf:"bytes,1,rep,name=server_ids,json=serverIds,proto3" json:"server_ids,omitempty"` // Empty = all servers
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanPlayerRequest) Reset() {
	*x = UnbanPlayerRequest{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanPlayerRequest) ProtoMessage() {}

func (x *UnbanPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanPlayerRequest.ProtoReflect.Descriptor instead.
func (*UnbanPlayerRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *UnbanPlayerRequest) GetServerIds() []string {
	if x != nil {
		return x.ServerIds
	}
	return nil
}

func (x *UnbanPlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Unban player response
type UnbanPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ServerOpResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanPlayerResponse) Reset() {
	*x = UnbanPlayerResponse{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanPlayerResponse) ProtoMessage() {}

func (x *UnbanPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanPlayerResponse.ProtoReflect.Descriptor instead.
func (*UnbanPlayerResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *UnbanPlayerResponse) GetResults() []*ServerOpResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// Get MOTD request
type GetServerMotdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerMotdRequest) Reset() {
	*x = GetServerMotdRequest{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerMotdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerMotdRequest) ProtoMessage() {}

func (x *GetServerMotdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerMotdRequest.ProtoReflect.Descriptor instead.
func (*GetServerMotdRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *GetServerMotdRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// Get MOTD response
type GetServerMotdResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Motd             string                 `protobuf:"bytes,1,opt,name=motd,proto3" json:"motd,omitempty"`                                                  // Raw motd value from server.properties (escaped \u00A7 etc.)
	Icon             string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`                                                  // Base64 PNG of icon.png, empty when absent
	WhitelistEnabled bool                   `protobuf:"varint,3,opt,name=whitelist_enabled,json=whitelistEnabled,proto3" json:"whitelist_enabled,omitempty"` // Current white-list setting in server.properties
	OnlineMode       bool                   `protobuf:"varint,4,opt,name=online_mode,json=onlineMode,proto3" json:"online_mode,omitempty"`                   // Current online-mode setting in server.properties
	MaxPlayers       int32                  `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`                   // Current max-players setting in server.properties
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetServerMotdResponse) Reset() {
	*x = GetServerMotdResponse{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerMotdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerMotdResponse) ProtoMessage() {}

func (x *GetServerMotdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerMotdResponse.ProtoReflect.Descriptor instead.
func (*GetServerMotdResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *GetServerMotdResponse) GetMotd() string {
	if x != nil {
		return x.Motd
	}
	return ""
}

func (x *GetServerMotdResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GetServerMotdResponse) GetWhitelistEnabled() bool {
	if x != nil {
		return x.WhitelistEnabled
	}
	return false
}

func (x *GetServerMotdResponse) GetOnlineMode() bool {
	if x != nil {
		return x.OnlineMode
	}
	return false
}

func (x *GetServerMotdResponse) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

// Update MOTD request
type UpdateServerMotdRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Motd             *string                `protobuf:"bytes,2,opt,name=motd,proto3,oneof" json:"motd,omitempty"`                                                  // Omit to leave unchanged
	Icon             *string                `protobuf:"bytes,3,opt,name=icon,proto3,oneof" json:"icon,omitempty"`                                                  // Base64 PNG; empty string removes icon.png
	WhitelistEnabled *bool                  `protobuf:"varint,4,opt,name=whitelist_enabled,json=whitelistEnabled,proto3,oneof" json:"whitelist_enabled,omitempty"` // Writes white-list=true/false and issues the RCON reload
	OnlineMode       *bool                  `protobuf:"varint,5,opt,name=online_mode,json=onlineMode,proto3,oneof" json:"online_mode,omitempty"`                   // Writes online-mode (requires restart)
	MaxPlayers       *int32                 `protobuf:"varint,6,opt,name=max_players,json=maxPlayers,proto3,oneof" json:"max_players,omitempty"`                   // Writes max-players (requires restart)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateServerMotdRequest) Reset() {
	*x = UpdateServerMotdRequest{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerMotdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerMotdRequest) ProtoMessage() {}

func (x *UpdateServerMotdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerMotdRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerMotdRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateServerMotdRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateServerMotdRequest) GetMotd() string {
	if x != nil && x.Motd != nil {
		return *x.Motd
	}
	return ""
}

func (x *UpdateServerMotdRequest) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *UpdateServerMotdRequest) GetWhitelistEnabled() bool {
	if x != nil && x.WhitelistEnabled != nil {
		return *x.WhitelistEnabled
	}
	return false
}

func (x *UpdateServerMotdRequest) GetOnlineMode() bool {
	if x != nil && x.OnlineMode != nil {
		return *x.OnlineMode
	}
	return false
}

func (x *UpdateServerMotdRequest) GetMaxPlayers() int32 {
	if x != nil && x.MaxPlayers != nil {
		return *x.MaxPlayers
	}
	return 0
}

// Update MOTD response
type UpdateServerMotdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "updated"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerMotdResponse) Reset() {
	*x = UpdateServerMotdResponse{}
	mi := &file_discopanel_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerMotdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerMotdResponse) ProtoMessage() {}

func (x *UpdateServerMotdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerMotdResponse.ProtoReflect.Descriptor instead.
func (*UpdateServerMotdResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateServerMotdResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_discopanel_v1_admin_proto protoreflect.FileDescriptor

const file_discopanel_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x19discopanel/v1/admin.proto\x12\rdiscopanel.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\x0eWhitelistEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xcc\x01\n" +
	"\x0eServerOpResult\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x14\n" +
	"\x05added\x18\x05 \x03(\tR\x05added\x12\x18\n" +
	"\aremoved\x18\x06 \x03(\tR\aremoved\x12\x18\n" +
	"\acurrent\x18\a \x03(\tR\acurrent\"5\n" +
	"\x1bListWhitelistEntriesRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\"W\n" +
	"\x1cListWhitelistEntriesResponse\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.discopanel.v1.WhitelistEntryR\aentries\"B\n" +
	"\x18AddWhitelistEntryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"P\n" +
	"\x19AddWhitelistEntryResponse\x123\n" +
	"\x05entry\x18\x01 \x01(\v2\x1d.discopanel.v1.WhitelistEntryR\x05entry\"-\n" +
	"\x1bRemoveWhitelistEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\x1cRemoveWhitelistEntryResponse\"6\n" +
	"\x15ApplyWhitelistRequest\x12\x1d\n" +
	"\n" +
	"server_ids\x18\x01 \x03(\tR\tserverIds\"Q\n" +
	"\x16ApplyWhitelistResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.discopanel.v1.ServerOpResultR\aresults\"3\n" +
	"\x14PullWhitelistRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"3\n" +
	"\x15PullWhitelistResponse\x12\x1a\n" +
	"\bimported\x18\x02 \x03(\tR\bimported\"]\n" +
	"\x10BanPlayerRequest\x12\x1d\n" +
	"\n" +
	"server_ids\x18\x01 \x03(\tR\tserverIds\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"L\n" +
	"\x11BanPlayerResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.discopanel.v1.ServerOpResultR\aresults\"G\n" +
	"\x12UnbanPlayerRequest\x12\x1d\n" +
	"\n" +
	"server_ids\x18\x01 \x03(\tR\tserverIds\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"N\n" +
	"\x13UnbanPlayerResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.discopanel.v1.ServerOpResultR\aresults\"3\n" +
	"\x14GetServerMotdRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\xae\x01\n" +
	"\x15GetServerMotdResponse\x12\x12\n" +
	"\x04motd\x18\x01 \x01(\tR\x04motd\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\x12+\n" +
	"\x11whitelist_enabled\x18\x03 \x01(\bR\x10whitelistEnabled\x12\x1f\n" +
	"\vonline_mode\x18\x04 \x01(\bR\n" +
	"onlineMode\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\x05R\n" +
	"maxPlayers\"\xae\x02\n" +
	"\x17UpdateServerMotdRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\x04motd\x18\x02 \x01(\tH\x00R\x04motd\x88\x01\x01\x12\x17\n" +
	"\x04icon\x18\x03 \x01(\tH\x01R\x04icon\x88\x01\x01\x120\n" +
	"\x11whitelist_enabled\x18\x04 \x01(\bH\x02R\x10whitelistEnabled\x88\x01\x01\x12$\n" +
	"\vonline_mode\x18\x05 \x01(\bH\x03R\n" +
	"onlineMode\x88\x01\x01\x12$\n" +
	"\vmax_players\x18\x06 \x01(\x05H\x04R\n" +
	"maxPlayers\x88\x01\x01B\a\n" +
	"\x05_motdB\a\n" +
	"\x05_iconB\x14\n" +
	"\x12_whitelist_enabledB\x0e\n" +
	"\f_online_modeB\x0e\n" +
	"\f_max_players\"2\n" +
	"\x18UpdateServerMotdResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xfa\x06\n" +
	"\fAdminService\x12o\n" +
	"\x14ListWhitelistEntries\x12*.discopanel.v1.ListWhitelistEntriesRequest\x1a+.discopanel.v1.ListWhitelistEntriesResponse\x12f\n" +
	"\x11AddWhitelistEntry\x12'.discopanel.v1.AddWhitelistEntryRequest\x1a(.discopanel.v1.AddWhitelistEntryResponse\x12o\n" +
	"\x14RemoveWhitelistEntry\x12*.discopanel.v1.RemoveWhitelistEntryRequest\x1a+.discopanel.v1.RemoveWhitelistEntryResponse\x12]\n" +
	"\x0eApplyWhitelist\x12$.discopanel.v1.ApplyWhitelistRequest\x1a%.discopanel.v1.ApplyWhitelistResponse\x12Z\n" +
	"\rPullWhitelist\x12#.discopanel.v1.PullWhitelistRequest\x1a$.discopanel.v1.PullWhitelistResponse\x12N\n" +
	"\tBanPlayer\x12\x1f.discopanel.v1.BanPlayerRequest\x1a .discopanel.v1.BanPlayerResponse\x12T\n" +
	"\vUnbanPlayer\x12!.discopanel.v1.UnbanPlayerRequest\x1a\".discopanel.v1.UnbanPlayerResponse\x12Z\n" +
	"\rGetServerMotd\x12#.discopanel.v1.GetServerMotdRequest\x1a$.discopanel.v1.GetServerMotdResponse\x12c\n" +
	"\x10UpdateServerMotd\x12&.discopanel.v1.UpdateServerMotdRequest\x1a'.discopanel.v1.UpdateServerMotdResponseBFZDgithub.com/nickheyer/discopanel/pkg/proto/discopanel/v1;discopanelv1b\x06proto3"

var (
	file_discopanel_v1_admin_proto_rawDescOnce sync.Once
	file_discopanel_v1_admin_proto_rawDescData []byte
)

func file_discopanel_v1_admin_proto_rawDescGZIP() []byte {
	file_discopanel_v1_admin_proto_rawDescOnce.Do(func() {
		file_discopanel_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discopanel_v1_admin_proto_rawDesc), len(file_discopanel_v1_admin_proto_rawDesc)))
	})
	return file_discopanel_v1_admin_proto_rawDescData
}

var file_discopanel_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_discopanel_v1_admin_proto_goTypes = []any{
	(*WhitelistEntry)(nil),               // 0: discopanel.v1.WhitelistEntry
	(*ServerOpResult)(nil),               // 1: discopanel.v1.ServerOpResult
	(*ListWhitelistEntriesRequest)(nil),  // 2: discopanel.v1.ListWhitelistEntriesRequest
	(*ListWhitelistEntriesResponse)(nil), // 3: discopanel.v1.ListWhitelistEntriesResponse
	(*AddWhitelistEntryRequest)(nil),     // 4: discopanel.v1.AddWhitelistEntryRequest
	(*AddWhitelistEntryResponse)(nil),    // 5: discopanel.v1.AddWhitelistEntryResponse
	(*RemoveWhitelistEntryRequest)(nil),  // 6: discopanel.v1.RemoveWhitelistEntryRequest
	(*RemoveWhitelistEntryResponse)(nil), // 7: discopanel.v1.RemoveWhitelistEntryResponse
	(*ApplyWhitelistRequest)(nil),        // 8: discopanel.v1.ApplyWhitelistRequest
	(*ApplyWhitelistResponse)(nil),       // 9: discopanel.v1.ApplyWhitelistResponse
	(*PullWhitelistRequest)(nil),         // 10: discopanel.v1.PullWhitelistRequest
	(*PullWhitelistResponse)(nil),        // 11: discopanel.v1.PullWhitelistResponse
	(*BanPlayerRequest)(nil),             // 12: discopanel.v1.BanPlayerRequest
	(*BanPlayerResponse)(nil),            // 13: discopanel.v1.BanPlayerResponse
	(*UnbanPlayerRequest)(nil),           // 14: discopanel.v1.UnbanPlayerRequest
	(*UnbanPlayerResponse)(nil),          // 15: discopanel.v1.UnbanPlayerResponse
	(*GetServerMotdRequest)(nil),         // 16: discopanel.v1.GetServerMotdRequest
	(*GetServerMotdResponse)(nil),        // 17: discopanel.v1.GetServerMotdResponse
	(*UpdateServerMotdRequest)(nil),      // 18: discopanel.v1.UpdateServerMotdRequest
	(*UpdateServerMotdResponse)(nil),     // 19: discopanel.v1.UpdateServerMotdResponse
	(*timestamppb.Timestamp)(nil),        // 20: google.protobuf.Timestamp
}
var file_discopanel_v1_admin_proto_depIdxs = []int32{
	20, // 0: discopanel.v1.WhitelistEntry.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: discopanel.v1.ListWhitelistEntriesResponse.entries:type_name -> discopanel.v1.WhitelistEntry
	0,  // 2: discopanel.v1.AddWhitelistEntryResponse.entry:type_name -> discopanel.v1.WhitelistEntry
	1,  // 3: discopanel.v1.ApplyWhitelistResponse.results:type_name -> discopanel.v1.ServerOpResult
	1,  // 4: discopanel.v1.BanPlayerResponse.results:type_name -> discopanel.v1.ServerOpResult
	1,  // 5: discopanel.v1.UnbanPlayerResponse.results:type_name -> discopanel.v1.ServerOpResult
	2,  // 6: discopanel.v1.AdminService.ListWhitelistEntries:input_type -> discopanel.v1.ListWhitelistEntriesRequest
	4,  // 7: discopanel.v1.AdminService.AddWhitelistEntry:input_type -> discopanel.v1.AddWhitelistEntryRequest
	6,  // 8: discopanel.v1.AdminService.RemoveWhitelistEntry:input_type -> discopanel.v1.RemoveWhitelistEntryRequest
	8,  // 9: discopanel.v1.AdminService.ApplyWhitelist:input_type -> discopanel.v1.ApplyWhitelistRequest
	10, // 10: discopanel.v1.AdminService.PullWhitelist:input_type -> discopanel.v1.PullWhitelistRequest
	12, // 11: discopanel.v1.AdminService.BanPlayer:input_type -> discopanel.v1.BanPlayerRequest
	14, // 12: discopanel.v1.AdminService.UnbanPlayer:input_type -> discopanel.v1.UnbanPlayerRequest
	16, // 13: discopanel.v1.AdminService.GetServerMotd:input_type -> discopanel.v1.GetServerMotdRequest
	18, // 14: discopanel.v1.AdminService.UpdateServerMotd:input_type -> discopanel.v1.UpdateServerMotdRequest
	3,  // 15: discopanel.v1.AdminService.ListWhitelistEntries:output_type -> discopanel.v1.ListWhitelistEntriesResponse
	5,  // 16: discopanel.v1.AdminService.AddWhitelistEntry:output_type -> discopanel.v1.AddWhitelistEntryResponse
	7,  // 17: discopanel.v1.AdminService.RemoveWhitelistEntry:output_type -> discopanel.v1.RemoveWhitelistEntryResponse
	9,  // 18: discopanel.v1.AdminService.ApplyWhitelist:output_type -> discopanel.v1.ApplyWhitelistResponse
	11, // 19: discopanel.v1.AdminService.PullWhitelist:output_type -> discopanel.v1.PullWhitelistResponse
	13, // 20: discopanel.v1.AdminService.BanPlayer:output_type -> discopanel.v1.BanPlayerResponse
	15, // 21: discopanel.v1.AdminService.UnbanPlayer:output_type -> discopanel.v1.UnbanPlayerResponse
	17, // 22: discopanel.v1.AdminService.GetServerMotd:output_type -> discopanel.v1.GetServerMotdResponse
	19, // 23: discopanel.v1.AdminService.UpdateServerMotd:output_type -> discopanel.v1.UpdateServerMotdResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_discopanel_v1_admin_proto_init() }
func file_discopanel_v1_admin_proto_init() {
	if File_discopanel_v1_admin_proto != nil {
		return
	}
	file_discopanel_v1_admin_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discopanel_v1_admin_proto_rawDesc), len(file_discopanel_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discopanel_v1_admin_proto_goTypes,
		DependencyIndexes: file_discopanel_v1_admin_proto_depIdxs,
		MessageInfos:      file_discopanel_v1_admin_proto_msgTypes,
	}.Build()
	File_discopanel_v1_admin_proto = out.File
	file_discopanel_v1_admin_proto_goTypes = nil
	file_discopanel_v1_admin_proto_depIdxs = nil
}
