// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: discopanel/v1/audit.proto

package discopanelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One recorded mutation
type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Procedure     string                 `protobuf:"bytes,4,opt,name=procedure,proto3" json:"procedure,omitempty"`               // e.g. /discopanel.v1.ServerService/StartServer
	Resource      string                 `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`                 // RBAC resource, e.g. servers
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`                     // RBAC action, e.g. start
	ObjectId      string                 `protobuf:"bytes,7,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"` // RBAC object id extracted from the request ("*" when none)
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                     // "ok" or "error"
	Detail        string                 `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail,omitempty"`                     // Error message when status is error, else empty
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_discopanel_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuditEntry) GetProcedure() string {
	if x != nil {
		return x.Procedure
	}
	return ""
}

func (x *AuditEntry) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *AuditEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuditEntry) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AuditEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// List audit entries request
type ListAuditEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // Optional filter
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"` // Optional filter
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`     // Optional filter
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`      // 0 = default 100
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditEntriesRequest) Reset() {
	*x = ListAuditEntriesRequest{}
	mi := &file_discopanel_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEntriesRequest) ProtoMessage() {}

func (x *ListAuditEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEntriesRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuditEntriesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuditEntriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// List audit entries response
type ListAuditEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditEntriesResponse) Reset() {
	*x = ListAuditEntriesResponse{}
	mi := &file_discopanel_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEntriesResponse) ProtoMessage() {}

func (x *ListAuditEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListAuditEntriesResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *ListAuditEntriesResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListAuditEntriesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Clear audit entries request
type ClearAuditEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=before,proto3,oneof" json:"before,omitempty"` // Omit to clear everything
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAuditEntriesRequest) Reset() {
	*x = ClearAuditEntriesRequest{}
	mi := &file_discopanel_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAuditEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAuditEntriesRequest) ProtoMessage() {}

func (x *ClearAuditEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAuditEntriesRequest.ProtoReflect.Descriptor instead.
func (*ClearAuditEntriesRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *ClearAuditEntriesRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

// Clear audit entries response
type ClearAuditEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAuditEntriesResponse) Reset() {
	*x = ClearAuditEntriesResponse{}
	mi := &file_discopanel_v1_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAuditEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAuditEntriesResponse) ProtoMessage() {}

func (x *ClearAuditEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAuditEntriesResponse.ProtoReflect.Descriptor instead.
func (*ClearAuditEntriesResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_audit_proto_rawDescGZIP(), []int{4}
}

func (x *ClearAuditEntriesResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_discopanel_v1_audit_proto protoreflect.FileDescriptor

const file_discopanel_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x19discopanel/v1/audit.proto\x12\rdiscopanel.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x02\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1c\n" +
	"\tprocedure\x18\x04 \x01(\tR\tprocedure\x12\x1a\n" +
	"\bresource\x18\x05 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1b\n" +
	"\tobject_id\x18\a \x01(\tR\bobjectId\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x16\n" +
	"\x06detail\x18\t \x01(\tR\x06detail\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x97\x01\n" +
	"\x17ListAuditEntriesRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"e\n" +
	"\x18ListAuditEntriesResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.discopanel.v1.AuditEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"^\n" +
	"\x18ClearAuditEntriesRequest\x127\n" +
	"\x06before\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x06before\x88\x01\x01B\t\n" +
	"\a_before\"5\n" +
	"\x19ClearAuditEntriesResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted2\xdb\x01\n" +
	"\fAuditService\x12c\n" +
	"\x10ListAuditEntries\x12&.discopanel.v1.ListAuditEntriesRequest\x1a'.discopanel.v1.ListAuditEntriesResponse\x12f\n" +
	"\x11ClearAuditEntries\x12'.discopanel.v1.ClearAuditEntriesRequest\x1a(.discopanel.v1.ClearAuditEntriesResponseBFZDgithub.com/nickheyer/discopanel/pkg/proto/discopanel/v1;discopanelv1b\x06proto3"

var (
	file_discopanel_v1_audit_proto_rawDescOnce sync.Once
	file_discopanel_v1_audit_proto_rawDescData []byte
)

func file_discopanel_v1_audit_proto_rawDescGZIP() []byte {
	file_discopanel_v1_audit_proto_rawDescOnce.Do(func() {
		file_discopanel_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discopanel_v1_audit_proto_rawDesc), len(file_discopanel_v1_audit_proto_rawDesc)))
	})
	return file_discopanel_v1_audit_proto_rawDescData
}

var file_discopanel_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_discopanel_v1_audit_proto_goTypes = []any{
	(*AuditEntry)(nil),                // 0: discopanel.v1.AuditEntry
	(*ListAuditEntriesRequest)(nil),   // 1: discopanel.v1.ListAuditEntriesRequest
	(*ListAuditEntriesResponse)(nil),  // 2: discopanel.v1.ListAuditEntriesResponse
	(*ClearAuditEntriesRequest)(nil),  // 3: discopanel.v1.ClearAuditEntriesRequest
	(*ClearAuditEntriesResponse)(nil), // 4: discopanel.v1.ClearAuditEntriesResponse
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
}
var file_discopanel_v1_audit_proto_depIdxs = []int32{
	5, // 0: discopanel.v1.AuditEntry.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: discopanel.v1.ListAuditEntriesResponse.entries:type_name -> discopanel.v1.AuditEntry
	5, // 2: discopanel.v1.ClearAuditEntriesRequest.before:type_name -> google.protobuf.Timestamp
	1, // 3: discopanel.v1.AuditService.ListAuditEntries:input_type -> discopanel.v1.ListAuditEntriesRequest
	3, // 4: discopanel.v1.AuditService.ClearAuditEntries:input_type -> discopanel.v1.ClearAuditEntriesRequest
	2, // 5: discopanel.v1.AuditService.ListAuditEntries:output_type -> discopanel.v1.ListAuditEntriesResponse
	4, // 6: discopanel.v1.AuditService.ClearAuditEntries:output_type -> discopanel.v1.ClearAuditEntriesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_discopanel_v1_audit_proto_init() }
func file_discopanel_v1_audit_proto_init() {
	if File_discopanel_v1_audit_proto != nil {
		return
	}
	file_discopanel_v1_audit_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discopanel_v1_audit_proto_rawDesc), len(file_discopanel_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discopanel_v1_audit_proto_goTypes,
		DependencyIndexes: file_discopanel_v1_audit_proto_depIdxs,
		MessageInfos:      file_discopanel_v1_audit_proto_msgTypes,
	}.Build()
	File_discopanel_v1_audit_proto = out.File
	file_discopanel_v1_audit_proto_goTypes = nil
	file_discopanel_v1_audit_proto_depIdxs = nil
}
