// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: discopanel/v1/player.proto

package discopanelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A known player
type Player struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FirstSeen         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	TotalPlaytimeSecs int64                  `protobuf:"varint,5,opt,name=total_playtime_secs,json=totalPlaytimeSecs,proto3" json:"total_playtime_secs,omitempty"` // Sum of completed session durations
	SessionsCount     int32                  `protobuf:"varint,6,opt,name=sessions_count,json=sessionsCount,proto3" json:"sessions_count,omitempty"`
	Online            bool                   `protobuf:"varint,7,opt,name=online,proto3" json:"online,omitempty"`                             // Currently connected through the proxy
	ServerStats       []*PlayerServerStats   `protobuf:"bytes,8,rep,name=server_stats,json=serverStats,proto3" json:"server_stats,omitempty"` // Per-server playtime
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_discopanel_v1_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Player) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Player) GetTotalPlaytimeSecs() int64 {
	if x != nil {
		return x.TotalPlaytimeSecs
	}
	return 0
}

func (x *Player) GetSessionsCount() int32 {
	if x != nil {
		return x.SessionsCount
	}
	return 0
}

func (x *Player) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Player) GetServerStats() []*PlayerServerStats {
	if x != nil {
		return x.ServerStats
	}
	return nil
}

// Per-server aggregate for a player
type PlayerServerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	PlaytimeSecs  int64                  `protobuf:"varint,3,opt,name=playtime_secs,json=playtimeSecs,proto3" json:"playtime_secs,omitempty"`
	SessionsCount int32                  `protobuf:"varint,4,opt,name=sessions_count,json=sessionsCount,proto3" json:"sessions_count,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerServerStats) Reset() {
	*x = PlayerServerStats{}
	mi := &file_discopanel_v1_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerServerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerServerStats) ProtoMessage() {}

func (x *PlayerServerStats) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerServerStats.ProtoReflect.Descriptor instead.
func (*PlayerServerStats) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerServerStats) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *PlayerServerStats) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *PlayerServerStats) GetPlaytimeSecs() int64 {
	if x != nil {
		return x.PlaytimeSecs
	}
	return 0
}

func (x *PlayerServerStats) GetSessionsCount() int32 {
	if x != nil {
		return x.SessionsCount
	}
	return 0
}

func (x *PlayerServerStats) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

// One play session on a server
type PlayerSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,3,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	ServerId      string                 `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LeftAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=left_at,json=leftAt,proto3,oneof" json:"left_at,omitempty"` // Null while still connected
	DurationSecs  int64                  `protobuf:"varint,8,opt,name=duration_secs,json=durationSecs,proto3" json:"duration_secs,omitempty"`
	BytesIn       int64                  `protobuf:"varint,9,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`     // Bytes transferred player -> server
	BytesOut      int64                  `protobuf:"varint,10,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"` // Bytes transferred server -> player
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSession) Reset() {
	*x = PlayerSession{}
	mi := &file_discopanel_v1_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSession) ProtoMessage() {}

func (x *PlayerSession) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSession.ProtoReflect.Descriptor instead.
func (*PlayerSession) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerSession) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerSession) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerSession) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *PlayerSession) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *PlayerSession) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *PlayerSession) GetLeftAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeftAt
	}
	return nil
}

func (x *PlayerSession) GetDurationSecs() int64 {
	if x != nil {
		return x.DurationSecs
	}
	return 0
}

func (x *PlayerSession) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *PlayerSession) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

// A player currently connected
type OnlinePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlinePlayer) Reset() {
	*x = OnlinePlayer{}
	mi := &file_discopanel_v1_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePlayer) ProtoMessage() {}

func (x *OnlinePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePlayer.ProtoReflect.Descriptor instead.
func (*OnlinePlayer) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{3}
}

func (x *OnlinePlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *OnlinePlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OnlinePlayer) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *OnlinePlayer) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *OnlinePlayer) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

// List players request
type ListPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // Filter to players who have played on this server
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`                     // Name substring search
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                      // 0 = default 100
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayersRequest) Reset() {
	*x = ListPlayersRequest{}
	mi := &file_discopanel_v1_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayersRequest) ProtoMessage() {}

func (x *ListPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayersRequest.ProtoReflect.Descriptor instead.
func (*ListPlayersRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{4}
}

func (x *ListPlayersRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListPlayersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListPlayersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPlayersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// List players response
type ListPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // Total matching before limit/offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayersResponse) Reset() {
	*x = ListPlayersResponse{}
	mi := &file_discopanel_v1_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayersResponse) ProtoMessage() {}

func (x *ListPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayersResponse.ProtoReflect.Descriptor instead.
func (*ListPlayersResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{5}
}

func (x *ListPlayersResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *ListPlayersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Get player request
type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_discopanel_v1_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlayerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Get player response
type GetPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Sessions      []*PlayerSession       `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"` // 20 most recent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerResponse) Reset() {
	*x = GetPlayerResponse{}
	mi := &file_discopanel_v1_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerResponse) ProtoMessage() {}

func (x *GetPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlayerResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *GetPlayerResponse) GetSessions() []*PlayerSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// List sessions request
type ListPlayerSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // Optional filter
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // Optional filter
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                      // 0 = default 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayerSessionsRequest) Reset() {
	*x = ListPlayerSessionsRequest{}
	mi := &file_discopanel_v1_player_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayerSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayerSessionsRequest) ProtoMessage() {}

func (x *ListPlayerSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayerSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListPlayerSessionsRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{8}
}

func (x *ListPlayerSessionsRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ListPlayerSessionsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListPlayerSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// List sessions response
type ListPlayerSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*PlayerSession       `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayerSessionsResponse) Reset() {
	*x = ListPlayerSessionsResponse{}
	mi := &file_discopanel_v1_player_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayerSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayerSessionsResponse) ProtoMessage() {}

func (x *ListPlayerSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayerSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListPlayerSessionsResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{9}
}

func (x *ListPlayerSessionsResponse) GetSessions() []*PlayerSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// List online players request
type ListOnlinePlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOnlinePlayersRequest) Reset() {
	*x = ListOnlinePlayersRequest{}
	mi := &file_discopanel_v1_player_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOnlinePlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOnlinePlayersRequest) ProtoMessage() {}

func (x *ListOnlinePlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOnlinePlayersRequest.ProtoReflect.Descriptor instead.
func (*ListOnlinePlayersRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{10}
}

func (x *ListOnlinePlayersRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// Online players response
type ListOnlinePlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*OnlinePlayer        `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOnlinePlayersResponse) Reset() {
	*x = ListOnlinePlayersResponse{}
	mi := &file_discopanel_v1_player_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOnlinePlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOnlinePlayersResponse) ProtoMessage() {}

func (x *ListOnlinePlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOnlinePlayersResponse.ProtoReflect.Descriptor instead.
func (*ListOnlinePlayersResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{11}
}

func (x *ListOnlinePlayersResponse) GetPlayers() []*OnlinePlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_discopanel_v1_player_proto protoreflect.FileDescriptor

const file_discopanel_v1_player_proto_rawDesc = "" +
	"\n" +
	"\x1adiscopanel/v1/player.proto\x12\rdiscopanel.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x02\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"first_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12.\n" +
	"\x13total_playtime_secs\x18\x05 \x01(\x03R\x11totalPlaytimeSecs\x12%\n" +
	"\x0esessions_count\x18\x06 \x01(\x05R\rsessionsCount\x12\x16\n" +
	"\x06online\x18\a \x01(\bR\x06online\x12C\n" +
	"\fserver_stats\x18\b \x03(\v2 .discopanel.v1.PlayerServerStatsR\vserverStats\"\xd6\x01\n" +
	"\x11PlayerServerStats\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12#\n" +
	"\rplaytime_secs\x18\x03 \x01(\x03R\fplaytimeSecs\x12%\n" +
	"\x0esessions_count\x18\x04 \x01(\x05R\rsessionsCount\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"\xf7\x02\n" +
	"\rPlayerSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x03 \x01(\tR\n" +
	"playerName\x12\x1b\n" +
	"\tserver_id\x18\x04 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\x127\n" +
	"\tjoined_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x128\n" +
	"\aleft_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x06leftAt\x88\x01\x01\x12#\n" +
	"\rduration_secs\x18\b \x01(\x03R\fdurationSecs\x12\x19\n" +
	"\bbytes_in\x18\t \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\n" +
	" \x01(\x03R\bbytesOutB\n" +
	"\n" +
	"\b_left_at\"\xb6\x01\n" +
	"\fOnlinePlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x04 \x01(\tR\n" +
	"serverName\x127\n" +
	"\tjoined_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"w\n" +
	"\x12ListPlayersRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\\\n" +
	"\x13ListPlayersResponse\x12/\n" +
	"\aplayers\x18\x01 \x03(\v2\x15.discopanel.v1.PlayerR\aplayers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\"\n" +
	"\x10GetPlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"|\n" +
	"\x11GetPlayerResponse\x12-\n" +
	"\x06player\x18\x01 \x01(\v2\x15.discopanel.v1.PlayerR\x06player\x128\n" +
	"\bsessions\x18\x02 \x03(\v2\x1c.discopanel.v1.PlayerSessionR\bsessions\"k\n" +
	"\x19ListPlayerSessionsRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"V\n" +
	"\x1aListPlayerSessionsResponse\x128\n" +
	"\bsessions\x18\x01 \x03(\v2\x1c.discopanel.v1.PlayerSessionR\bsessions\"7\n" +
	"\x18ListOnlinePlayersRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"R\n" +
	"\x19ListOnlinePlayersResponse\x125\n" +
	"\aplayers\x18\x01 \x03(\v2\x1b.discopanel.v1.OnlinePlayerR\aplayers2\x88\x03\n" +
	"\rPlayerService\x12T\n" +
	"\vListPlayers\x12!.discopanel.v1.ListPlayersRequest\x1a\".discopanel.v1.ListPlayersResponse\x12N\n" +
	"\tGetPlayer\x12\x1f.discopanel.v1.GetPlayerRequest\x1a .discopanel.v1.GetPlayerResponse\x12i\n" +
	"\x12ListPlayerSessions\x12(.discopanel.v1.ListPlayerSessionsRequest\x1a).discopanel.v1.ListPlayerSessionsResponse\x12f\n" +
	"\x11ListOnlinePlayers\x12'.discopanel.v1.ListOnlinePlayersRequest\x1a(.discopanel.v1.ListOnlinePlayersResponseBFZDgithub.com/nickheyer/discopanel/pkg/proto/discopanel/v1;discopanelv1b\x06proto3"

var (
	file_discopanel_v1_player_proto_rawDescOnce sync.Once
	file_discopanel_v1_player_proto_rawDescData []byte
)

func file_discopanel_v1_player_proto_rawDescGZIP() []byte {
	file_discopanel_v1_player_proto_rawDescOnce.Do(func() {
		file_discopanel_v1_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discopanel_v1_player_proto_rawDesc), len(file_discopanel_v1_player_proto_rawDesc)))
	})
	return file_discopanel_v1_player_proto_rawDescData
}

var file_discopanel_v1_player_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_discopanel_v1_player_proto_goTypes = []any{
	(*Player)(nil),                     // 0: discopanel.v1.Player
	(*PlayerServerStats)(nil),          // 1: discopanel.v1.PlayerServerStats
	(*PlayerSession)(nil),              // 2: discopanel.v1.PlayerSession
	(*OnlinePlayer)(nil),               // 3: discopanel.v1.OnlinePlayer
	(*ListPlayersRequest)(nil),         // 4: discopanel.v1.ListPlayersRequest
	(*ListPlayersResponse)(nil),        // 5: discopanel.v1.ListPlayersResponse
	(*GetPlayerRequest)(nil),           // 6: discopanel.v1.GetPlayerRequest
	(*GetPlayerResponse)(nil),          // 7: discopanel.v1.GetPlayerResponse
	(*ListPlayerSessionsRequest)(nil),  // 8: discopanel.v1.ListPlayerSessionsRequest
	(*ListPlayerSessionsResponse)(nil), // 9: discopanel.v1.ListPlayerSessionsResponse
	(*ListOnlinePlayersRequest)(nil),   // 10: discopanel.v1.ListOnlinePlayersRequest
	(*ListOnlinePlayersResponse)(nil),  // 11: discopanel.v1.ListOnlinePlayersResponse
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
}
var file_discopanel_v1_player_proto_depIdxs = []int32{
	12, // 0: discopanel.v1.Player.first_seen:type_name -> google.protobuf.Timestamp
	12, // 1: discopanel.v1.Player.last_seen:type_name -> google.protobuf.Timestamp
	1,  // 2: discopanel.v1.Player.server_stats:type_name -> discopanel.v1.PlayerServerStats
	12, // 3: discopanel.v1.PlayerServerStats.last_seen:type_name -> google.protobuf.Timestamp
	12, // 4: discopanel.v1.PlayerSession.joined_at:type_name -> google.protobuf.Timestamp
	12, // 5: discopanel.v1.PlayerSession.left_at:type_name -> google.protobuf.Timestamp
	12, // 6: discopanel.v1.OnlinePlayer.joined_at:type_name -> google.protobuf.Timestamp
	0,  // 7: discopanel.v1.ListPlayersResponse.players:type_name -> discopanel.v1.Player
	0,  // 8: discopanel.v1.GetPlayerResponse.player:type_name -> discopanel.v1.Player
	2,  // 9: discopanel.v1.GetPlayerResponse.sessions:type_name -> discopanel.v1.PlayerSession
	2,  // 10: discopanel.v1.ListPlayerSessionsResponse.sessions:type_name -> discopanel.v1.PlayerSession
	3,  // 11: discopanel.v1.ListOnlinePlayersResponse.players:type_name -> discopanel.v1.OnlinePlayer
	4,  // 12: discopanel.v1.PlayerService.ListPlayers:input_type -> discopanel.v1.ListPlayersRequest
	6,  // 13: discopanel.v1.PlayerService.GetPlayer:input_type -> discopanel.v1.GetPlayerRequest
	8,  // 14: discopanel.v1.PlayerService.ListPlayerSessions:input_type -> discopanel.v1.ListPlayerSessionsRequest
	10, // 15: discopanel.v1.PlayerService.ListOnlinePlayers:input_type -> discopanel.v1.ListOnlinePlayersRequest
	5,  // 16: discopanel.v1.PlayerService.ListPlayers:output_type -> discopanel.v1.ListPlayersResponse
	7,  // 17: discopanel.v1.PlayerService.GetPlayer:output_type -> discopanel.v1.GetPlayerResponse
	9,  // 18: discopanel.v1.PlayerService.ListPlayerSessions:output_type -> discopanel.v1.ListPlayerSessionsResponse
	11, // 19: discopanel.v1.PlayerService.ListOnlinePlayers:output_type -> discopanel.v1.ListOnlinePlayersResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_discopanel_v1_player_proto_init() }
func file_discopanel_v1_player_proto_init() {
	if File_discopanel_v1_player_proto != nil {
		return
	}
	file_discopanel_v1_player_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discopanel_v1_player_proto_rawDesc), len(file_discopanel_v1_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discopanel_v1_player_proto_goTypes,
		DependencyIndexes: file_discopanel_v1_player_proto_depIdxs,
		MessageInfos:      file_discopanel_v1_player_proto_msgTypes,
	}.Build()
	File_discopanel_v1_player_proto = out.File
	file_discopanel_v1_player_proto_goTypes = nil
	file_discopanel_v1_player_proto_depIdxs = nil
}
