// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: discopanel/v1/player.proto

package discopanelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Moderation actions available for players
type PlayerAction int32

const (
	PlayerAction_PLAYER_ACTION_UNSPECIFIED PlayerAction = 0
	// Add the player to the whitelist
	PlayerAction_PLAYER_ACTION_WHITELIST_ADD PlayerAction = 1
	// Remove the player from the whitelist
	PlayerAction_PLAYER_ACTION_WHITELIST_REMOVE PlayerAction = 2
	// Grant operator status
	PlayerAction_PLAYER_ACTION_OP PlayerAction = 3
	// Revoke operator status
	PlayerAction_PLAYER_ACTION_DEOP PlayerAction = 4
	// Ban the player
	PlayerAction_PLAYER_ACTION_BAN PlayerAction = 5
	// Lift a ban (pardon)
	PlayerAction_PLAYER_ACTION_UNBAN PlayerAction = 6
	// Kick the player from the server
	PlayerAction_PLAYER_ACTION_KICK PlayerAction = 7
)

// Enum value maps for PlayerAction.
var (
	PlayerAction_name = map[int32]string{
		0: "PLAYER_ACTION_UNSPECIFIED",
		1: "PLAYER_ACTION_WHITELIST_ADD",
		2: "PLAYER_ACTION_WHITELIST_REMOVE",
		3: "PLAYER_ACTION_OP",
		4: "PLAYER_ACTION_DEOP",
		5: "PLAYER_ACTION_BAN",
		6: "PLAYER_ACTION_UNBAN",
		7: "PLAYER_ACTION_KICK",
	}
	PlayerAction_value = map[string]int32{
		"PLAYER_ACTION_UNSPECIFIED":      0,
		"PLAYER_ACTION_WHITELIST_ADD":    1,
		"PLAYER_ACTION_WHITELIST_REMOVE": 2,
		"PLAYER_ACTION_OP":               3,
		"PLAYER_ACTION_DEOP":             4,
		"PLAYER_ACTION_BAN":              5,
		"PLAYER_ACTION_UNBAN":            6,
		"PLAYER_ACTION_KICK":             7,
	}
)

func (x PlayerAction) Enum() *PlayerAction {
	p := new(PlayerAction)
	*p = x
	return p
}

func (x PlayerAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerAction) Descriptor() protoreflect.EnumDescriptor {
	return file_discopanel_v1_player_proto_enumTypes[0].Descriptor()
}

func (PlayerAction) Type() protoreflect.EnumType {
	return &file_discopanel_v1_player_proto_enumTypes[0]
}

func (x PlayerAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerAction.Descriptor instead.
func (PlayerAction) EnumDescriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{0}
}

// Online players request
type ListOnlinePlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOnlinePlayersRequest) Reset() {
	*x = ListOnlinePlayersRequest{}
	mi := &file_discopanel_v1_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOnlinePlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOnlinePlayersRequest) ProtoMessage() {}

func (x *ListOnlinePlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOnlinePlayersRequest.ProtoReflect.Descriptor instead.
func (*ListOnlinePlayersRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{0}
}

func (x *ListOnlinePlayersRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type OnlinePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlinePlayer) Reset() {
	*x = OnlinePlayer{}
	mi := &file_discopanel_v1_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePlayer) ProtoMessage() {}

func (x *OnlinePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePlayer.ProtoReflect.Descriptor instead.
func (*OnlinePlayer) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{1}
}

func (x *OnlinePlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Players currently online
type ListOnlinePlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*OnlinePlayer        `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOnlinePlayersResponse) Reset() {
	*x = ListOnlinePlayersResponse{}
	mi := &file_discopanel_v1_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOnlinePlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOnlinePlayersResponse) ProtoMessage() {}

func (x *ListOnlinePlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOnlinePlayersResponse.ProtoReflect.Descriptor instead.
func (*ListOnlinePlayersResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{2}
}

func (x *ListOnlinePlayersResponse) GetPlayers() []*OnlinePlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

// Player action parameters
type ManagePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Action        PlayerAction           `protobuf:"varint,3,opt,name=action,proto3,enum=discopanel.v1.PlayerAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagePlayerRequest) Reset() {
	*x = ManagePlayerRequest{}
	mi := &file_discopanel_v1_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagePlayerRequest) ProtoMessage() {}

func (x *ManagePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagePlayerRequest.ProtoReflect.Descriptor instead.
func (*ManagePlayerRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{3}
}

func (x *ManagePlayerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ManagePlayerRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *ManagePlayerRequest) GetAction() PlayerAction {
	if x != nil {
		return x.Action
	}
	return PlayerAction_PLAYER_ACTION_UNSPECIFIED
}

// Command output from the action
type ManagePlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagePlayerResponse) Reset() {
	*x = ManagePlayerResponse{}
	mi := &file_discopanel_v1_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagePlayerResponse) ProtoMessage() {}

func (x *ManagePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagePlayerResponse.ProtoReflect.Descriptor instead.
func (*ManagePlayerResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_player_proto_rawDescGZIP(), []int{4}
}

func (x *ManagePlayerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ManagePlayerResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ManagePlayerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_discopanel_v1_player_proto protoreflect.FileDescriptor

const file_discopanel_v1_player_proto_rawDesc = "" +
	"\n" +
	"\x1adiscopanel/v1/player.proto\x12\rdiscopanel.v1\"7\n" +
	"\x18ListOnlinePlayersRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\"\n" +
	"\fOnlinePlayer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"R\n" +
	"\x19ListOnlinePlayersResponse\x125\n" +
	"\aplayers\x18\x01 \x03(\v2\x1b.discopanel.v1.OnlinePlayerR\aplayers\"\x88\x01\n" +
	"\x13ManagePlayerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x123\n" +
	"\x06action\x18\x03 \x01(\x0e2\x1b.discopanel.v1.PlayerActionR\x06action\"^\n" +
	"\x14ManagePlayerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*\xe8\x01\n" +
	"\fPlayerAction\x12\x1d\n" +
	"\x19PLAYER_ACTION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPLAYER_ACTION_WHITELIST_ADD\x10\x01\x12\"\n" +
	"\x1ePLAYER_ACTION_WHITELIST_REMOVE\x10\x02\x12\x14\n" +
	"\x10PLAYER_ACTION_OP\x10\x03\x12\x16\n" +
	"\x12PLAYER_ACTION_DEOP\x10\x04\x12\x15\n" +
	"\x11PLAYER_ACTION_BAN\x10\x05\x12\x17\n" +
	"\x13PLAYER_ACTION_UNBAN\x10\x06\x12\x16\n" +
	"\x12PLAYER_ACTION_KICK\x10\a2\xd0\x01\n" +
	"\rPlayerService\x12f\n" +
	"\x11ListOnlinePlayers\x12'.discopanel.v1.ListOnlinePlayersRequest\x1a(.discopanel.v1.ListOnlinePlayersResponse\x12W\n" +
	"\fManagePlayer\x12\".discopanel.v1.ManagePlayerRequest\x1a#.discopanel.v1.ManagePlayerResponseBFZDgithub.com/nickheyer/discopanel/pkg/proto/discopanel/v1;discopanelv1b\x06proto3"

var (
	file_discopanel_v1_player_proto_rawDescOnce sync.Once
	file_discopanel_v1_player_proto_rawDescData []byte
)

func file_discopanel_v1_player_proto_rawDescGZIP() []byte {
	file_discopanel_v1_player_proto_rawDescOnce.Do(func() {
		file_discopanel_v1_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discopanel_v1_player_proto_rawDesc), len(file_discopanel_v1_player_proto_rawDesc)))
	})
	return file_discopanel_v1_player_proto_rawDescData
}

var file_discopanel_v1_player_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_discopanel_v1_player_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_discopanel_v1_player_proto_goTypes = []any{
	(PlayerAction)(0),                 // 0: discopanel.v1.PlayerAction
	(*ListOnlinePlayersRequest)(nil),  // 1: discopanel.v1.ListOnlinePlayersRequest
	(*OnlinePlayer)(nil),              // 2: discopanel.v1.OnlinePlayer
	(*ListOnlinePlayersResponse)(nil), // 3: discopanel.v1.ListOnlinePlayersResponse
	(*ManagePlayerRequest)(nil),       // 4: discopanel.v1.ManagePlayerRequest
	(*ManagePlayerResponse)(nil),      // 5: discopanel.v1.ManagePlayerResponse
}
var file_discopanel_v1_player_proto_depIdxs = []int32{
	2, // 0: discopanel.v1.ListOnlinePlayersResponse.players:type_name -> discopanel.v1.OnlinePlayer
	0, // 1: discopanel.v1.ManagePlayerRequest.action:type_name -> discopanel.v1.PlayerAction
	1, // 2: discopanel.v1.PlayerService.ListOnlinePlayers:input_type -> discopanel.v1.ListOnlinePlayersRequest
	4, // 3: discopanel.v1.PlayerService.ManagePlayer:input_type -> discopanel.v1.ManagePlayerRequest
	3, // 4: discopanel.v1.PlayerService.ListOnlinePlayers:output_type -> discopanel.v1.ListOnlinePlayersResponse
	5, // 5: discopanel.v1.PlayerService.ManagePlayer:output_type -> discopanel.v1.ManagePlayerResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_discopanel_v1_player_proto_init() }
func file_discopanel_v1_player_proto_init() {
	if File_discopanel_v1_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discopanel_v1_player_proto_rawDesc), len(file_discopanel_v1_player_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discopanel_v1_player_proto_goTypes,
		DependencyIndexes: file_discopanel_v1_player_proto_depIdxs,
		EnumInfos:         file_discopanel_v1_player_proto_enumTypes,
		MessageInfos:      file_discopanel_v1_player_proto_msgTypes,
	}.Build()
	File_discopanel_v1_player_proto = out.File
	file_discopanel_v1_player_proto_goTypes = nil
	file_discopanel_v1_player_proto_depIdxs = nil
}
