// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: discopanel/v1/tunnel.proto

package discopanelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TunnelProvider specifies the backend tunneling service
type TunnelProvider int32

const (
	TunnelProvider_TUNNEL_PROVIDER_UNSPECIFIED TunnelProvider = 0
	TunnelProvider_TUNNEL_PROVIDER_PLAYIT      TunnelProvider = 1
)

// Enum value maps for TunnelProvider.
var (
	TunnelProvider_name = map[int32]string{
		0: "TUNNEL_PROVIDER_UNSPECIFIED",
		1: "TUNNEL_PROVIDER_PLAYIT",
	}
	TunnelProvider_value = map[string]int32{
		"TUNNEL_PROVIDER_UNSPECIFIED": 0,
		"TUNNEL_PROVIDER_PLAYIT":      1,
	}
)

func (x TunnelProvider) Enum() *TunnelProvider {
	p := new(TunnelProvider)
	*p = x
	return p
}

func (x TunnelProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_discopanel_v1_tunnel_proto_enumTypes[0].Descriptor()
}

func (TunnelProvider) Type() protoreflect.EnumType {
	return &file_discopanel_v1_tunnel_proto_enumTypes[0]
}

func (x TunnelProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelProvider.Descriptor instead.
func (TunnelProvider) EnumDescriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

// TunnelStatus represents the runtime state of a tunnel
type TunnelStatus int32

const (
	TunnelStatus_TUNNEL_STATUS_UNSPECIFIED   TunnelStatus = 0
	TunnelStatus_TUNNEL_STATUS_STOPPED       TunnelStatus = 1
	TunnelStatus_TUNNEL_STATUS_STARTING      TunnelStatus = 2
	TunnelStatus_TUNNEL_STATUS_CLAIM_PENDING TunnelStatus = 3
	TunnelStatus_TUNNEL_STATUS_RUNNING       TunnelStatus = 4
	TunnelStatus_TUNNEL_STATUS_ERROR         TunnelStatus = 5
)

// Enum value maps for TunnelStatus.
var (
	TunnelStatus_name = map[int32]string{
		0: "TUNNEL_STATUS_UNSPECIFIED",
		1: "TUNNEL_STATUS_STOPPED",
		2: "TUNNEL_STATUS_STARTING",
		3: "TUNNEL_STATUS_CLAIM_PENDING",
		4: "TUNNEL_STATUS_RUNNING",
		5: "TUNNEL_STATUS_ERROR",
	}
	TunnelStatus_value = map[string]int32{
		"TUNNEL_STATUS_UNSPECIFIED":   0,
		"TUNNEL_STATUS_STOPPED":       1,
		"TUNNEL_STATUS_STARTING":      2,
		"TUNNEL_STATUS_CLAIM_PENDING": 3,
		"TUNNEL_STATUS_RUNNING":       4,
		"TUNNEL_STATUS_ERROR":         5,
	}
)

func (x TunnelStatus) Enum() *TunnelStatus {
	p := new(TunnelStatus)
	*p = x
	return p
}

func (x TunnelStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_discopanel_v1_tunnel_proto_enumTypes[1].Descriptor()
}

func (TunnelStatus) Type() protoreflect.EnumType {
	return &file_discopanel_v1_tunnel_proto_enumTypes[1]
}

func (x TunnelStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelStatus.Descriptor instead.
func (TunnelStatus) EnumDescriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{1}
}

// TunnelProtocol represents transport protocol
type TunnelProtocol int32

const (
	TunnelProtocol_TUNNEL_PROTOCOL_UNSPECIFIED TunnelProtocol = 0
	TunnelProtocol_TUNNEL_PROTOCOL_TCP         TunnelProtocol = 1
	TunnelProtocol_TUNNEL_PROTOCOL_UDP         TunnelProtocol = 2
	TunnelProtocol_TUNNEL_PROTOCOL_BOTH        TunnelProtocol = 3
)

// Enum value maps for TunnelProtocol.
var (
	TunnelProtocol_name = map[int32]string{
		0: "TUNNEL_PROTOCOL_UNSPECIFIED",
		1: "TUNNEL_PROTOCOL_TCP",
		2: "TUNNEL_PROTOCOL_UDP",
		3: "TUNNEL_PROTOCOL_BOTH",
	}
	TunnelProtocol_value = map[string]int32{
		"TUNNEL_PROTOCOL_UNSPECIFIED": 0,
		"TUNNEL_PROTOCOL_TCP":         1,
		"TUNNEL_PROTOCOL_UDP":         2,
		"TUNNEL_PROTOCOL_BOTH":        3,
	}
)

func (x TunnelProtocol) Enum() *TunnelProtocol {
	p := new(TunnelProtocol)
	*p = x
	return p
}

func (x TunnelProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_discopanel_v1_tunnel_proto_enumTypes[2].Descriptor()
}

func (TunnelProtocol) Type() protoreflect.EnumType {
	return &file_discopanel_v1_tunnel_proto_enumTypes[2]
}

func (x TunnelProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelProtocol.Descriptor instead.
func (TunnelProtocol) EnumDescriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{2}
}

// Tunnel represents a configured tunnel instance
type Tunnel struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId              string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName            string                 `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Provider              TunnelProvider         `protobuf:"varint,4,opt,name=provider,proto3,enum=discopanel.v1.TunnelProvider" json:"provider,omitempty"`
	Name                  string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Protocol              TunnelProtocol         `protobuf:"varint,6,opt,name=protocol,proto3,enum=discopanel.v1.TunnelProtocol" json:"protocol,omitempty"`
	TargetHost            string                 `protobuf:"bytes,7,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort            int32                  `protobuf:"varint,8,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	ContainerId           string                 `protobuf:"bytes,9,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status                TunnelStatus           `protobuf:"varint,10,opt,name=status,proto3,enum=discopanel.v1.TunnelStatus" json:"status,omitempty"`
	ClaimUrl              string                 `protobuf:"bytes,11,opt,name=claim_url,json=claimUrl,proto3" json:"claim_url,omitempty"`
	ClaimCode             string                 `protobuf:"bytes,12,opt,name=claim_code,json=claimCode,proto3" json:"claim_code,omitempty"`
	IsAccountLinked       bool                   `protobuf:"varint,13,opt,name=is_account_linked,json=isAccountLinked,proto3" json:"is_account_linked,omitempty"`
	PublicAddress         string                 `protobuf:"bytes,14,opt,name=public_address,json=publicAddress,proto3" json:"public_address,omitempty"`
	PublicPort            int32                  `protobuf:"varint,15,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	AutoStart             bool                   `protobuf:"varint,16,opt,name=auto_start,json=autoStart,proto3" json:"auto_start,omitempty"`
	FollowServerLifecycle bool                   `protobuf:"varint,17,opt,name=follow_server_lifecycle,json=followServerLifecycle,proto3" json:"follow_server_lifecycle,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Tunnel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tunnel) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Tunnel) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Tunnel) GetProvider() TunnelProvider {
	if x != nil {
		return x.Provider
	}
	return TunnelProvider_TUNNEL_PROVIDER_UNSPECIFIED
}

func (x *Tunnel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tunnel) GetProtocol() TunnelProtocol {
	if x != nil {
		return x.Protocol
	}
	return TunnelProtocol_TUNNEL_PROTOCOL_UNSPECIFIED
}

func (x *Tunnel) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *Tunnel) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *Tunnel) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Tunnel) GetStatus() TunnelStatus {
	if x != nil {
		return x.Status
	}
	return TunnelStatus_TUNNEL_STATUS_UNSPECIFIED
}

func (x *Tunnel) GetClaimUrl() string {
	if x != nil {
		return x.ClaimUrl
	}
	return ""
}

func (x *Tunnel) GetClaimCode() string {
	if x != nil {
		return x.ClaimCode
	}
	return ""
}

func (x *Tunnel) GetIsAccountLinked() bool {
	if x != nil {
		return x.IsAccountLinked
	}
	return false
}

func (x *Tunnel) GetPublicAddress() string {
	if x != nil {
		return x.PublicAddress
	}
	return ""
}

func (x *Tunnel) GetPublicPort() int32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *Tunnel) GetAutoStart() bool {
	if x != nil {
		return x.AutoStart
	}
	return false
}

func (x *Tunnel) GetFollowServerLifecycle() bool {
	if x != nil {
		return x.FollowServerLifecycle
	}
	return false
}

func (x *Tunnel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tunnel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetServerTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerTunnelsRequest) Reset() {
	*x = GetServerTunnelsRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerTunnelsRequest) ProtoMessage() {}

func (x *GetServerTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerTunnelsRequest.ProtoReflect.Descriptor instead.
func (*GetServerTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerTunnelsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetServerTunnelsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tunnels          []*Tunnel              `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	HasGlobalAccount bool                   `protobuf:"varint,2,opt,name=has_global_account,json=hasGlobalAccount,proto3" json:"has_global_account,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetServerTunnelsResponse) Reset() {
	*x = GetServerTunnelsResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerTunnelsResponse) ProtoMessage() {}

func (x *GetServerTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerTunnelsResponse.ProtoReflect.Descriptor instead.
func (*GetServerTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *GetServerTunnelsResponse) GetTunnels() []*Tunnel {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

func (x *GetServerTunnelsResponse) GetHasGlobalAccount() bool {
	if x != nil {
		return x.HasGlobalAccount
	}
	return false
}

type ListTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsRequest) Reset() {
	*x = ListTunnelsRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsRequest) ProtoMessage() {}

func (x *ListTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsRequest.ProtoReflect.Descriptor instead.
func (*ListTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{3}
}

type ListTunnelsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tunnels          []*Tunnel              `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	HasGlobalAccount bool                   `protobuf:"varint,2,opt,name=has_global_account,json=hasGlobalAccount,proto3" json:"has_global_account,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTunnelsResponse) Reset() {
	*x = ListTunnelsResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsResponse) ProtoMessage() {}

func (x *ListTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsResponse.ProtoReflect.Descriptor instead.
func (*ListTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *ListTunnelsResponse) GetTunnels() []*Tunnel {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

func (x *ListTunnelsResponse) GetHasGlobalAccount() bool {
	if x != nil {
		return x.HasGlobalAccount
	}
	return false
}

type GetTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelRequest) Reset() {
	*x = GetTunnelRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelRequest) ProtoMessage() {}

func (x *GetTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelRequest.ProtoReflect.Descriptor instead.
func (*GetTunnelRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *GetTunnelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelResponse) Reset() {
	*x = GetTunnelResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelResponse) ProtoMessage() {}

func (x *GetTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelResponse.ProtoReflect.Descriptor instead.
func (*GetTunnelResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *GetTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type CreateTunnelRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServerId              string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider              TunnelProvider         `protobuf:"varint,3,opt,name=provider,proto3,enum=discopanel.v1.TunnelProvider" json:"provider,omitempty"`
	Protocol              TunnelProtocol         `protobuf:"varint,4,opt,name=protocol,proto3,enum=discopanel.v1.TunnelProtocol" json:"protocol,omitempty"`
	TargetPort            int32                  `protobuf:"varint,5,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	TargetHost            *string                `protobuf:"bytes,6,opt,name=target_host,json=targetHost,proto3,oneof" json:"target_host,omitempty"`
	AutoStart             *bool                  `protobuf:"varint,7,opt,name=auto_start,json=autoStart,proto3,oneof" json:"auto_start,omitempty"`
	FollowServerLifecycle *bool                  `protobuf:"varint,8,opt,name=follow_server_lifecycle,json=followServerLifecycle,proto3,oneof" json:"follow_server_lifecycle,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateTunnelRequest) Reset() {
	*x = CreateTunnelRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTunnelRequest) ProtoMessage() {}

func (x *CreateTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTunnelRequest.ProtoReflect.Descriptor instead.
func (*CreateTunnelRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTunnelRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateTunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTunnelRequest) GetProvider() TunnelProvider {
	if x != nil {
		return x.Provider
	}
	return TunnelProvider_TUNNEL_PROVIDER_UNSPECIFIED
}

func (x *CreateTunnelRequest) GetProtocol() TunnelProtocol {
	if x != nil {
		return x.Protocol
	}
	return TunnelProtocol_TUNNEL_PROTOCOL_UNSPECIFIED
}

func (x *CreateTunnelRequest) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *CreateTunnelRequest) GetTargetHost() string {
	if x != nil && x.TargetHost != nil {
		return *x.TargetHost
	}
	return ""
}

func (x *CreateTunnelRequest) GetAutoStart() bool {
	if x != nil && x.AutoStart != nil {
		return *x.AutoStart
	}
	return false
}

func (x *CreateTunnelRequest) GetFollowServerLifecycle() bool {
	if x != nil && x.FollowServerLifecycle != nil {
		return *x.FollowServerLifecycle
	}
	return false
}

type CreateTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTunnelResponse) Reset() {
	*x = CreateTunnelResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTunnelResponse) ProtoMessage() {}

func (x *CreateTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTunnelResponse.ProtoReflect.Descriptor instead.
func (*CreateTunnelResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type UpdateTunnelRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	AutoStart             *bool                  `protobuf:"varint,3,opt,name=auto_start,json=autoStart,proto3,oneof" json:"auto_start,omitempty"`
	FollowServerLifecycle *bool                  `protobuf:"varint,4,opt,name=follow_server_lifecycle,json=followServerLifecycle,proto3,oneof" json:"follow_server_lifecycle,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateTunnelRequest) Reset() {
	*x = UpdateTunnelRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTunnelRequest) ProtoMessage() {}

func (x *UpdateTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTunnelRequest.ProtoReflect.Descriptor instead.
func (*UpdateTunnelRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTunnelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTunnelRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTunnelRequest) GetAutoStart() bool {
	if x != nil && x.AutoStart != nil {
		return *x.AutoStart
	}
	return false
}

func (x *UpdateTunnelRequest) GetFollowServerLifecycle() bool {
	if x != nil && x.FollowServerLifecycle != nil {
		return *x.FollowServerLifecycle
	}
	return false
}

type UpdateTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTunnelResponse) Reset() {
	*x = UpdateTunnelResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTunnelResponse) ProtoMessage() {}

func (x *UpdateTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTunnelResponse.ProtoReflect.Descriptor instead.
func (*UpdateTunnelResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type DeleteTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTunnelRequest) Reset() {
	*x = DeleteTunnelRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTunnelRequest) ProtoMessage() {}

func (x *DeleteTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTunnelRequest.ProtoReflect.Descriptor instead.
func (*DeleteTunnelRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTunnelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTunnelResponse) Reset() {
	*x = DeleteTunnelResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTunnelResponse) ProtoMessage() {}

func (x *DeleteTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTunnelResponse.ProtoReflect.Descriptor instead.
func (*DeleteTunnelResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTunnelResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StartTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTunnelRequest) Reset() {
	*x = StartTunnelRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelRequest) ProtoMessage() {}

func (x *StartTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelRequest.ProtoReflect.Descriptor instead.
func (*StartTunnelRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{13}
}

func (x *StartTunnelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTunnelResponse) Reset() {
	*x = StartTunnelResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelResponse) ProtoMessage() {}

func (x *StartTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelResponse.ProtoReflect.Descriptor instead.
func (*StartTunnelResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{14}
}

func (x *StartTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type StopTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTunnelRequest) Reset() {
	*x = StopTunnelRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTunnelRequest) ProtoMessage() {}

func (x *StopTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTunnelRequest.ProtoReflect.Descriptor instead.
func (*StopTunnelRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{15}
}

func (x *StopTunnelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTunnelResponse) Reset() {
	*x = StopTunnelResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTunnelResponse) ProtoMessage() {}

func (x *StopTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTunnelResponse.ProtoReflect.Descriptor instead.
func (*StopTunnelResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{16}
}

func (x *StopTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type RestartTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTunnelRequest) Reset() {
	*x = RestartTunnelRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTunnelRequest) ProtoMessage() {}

func (x *RestartTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTunnelRequest.ProtoReflect.Descriptor instead.
func (*RestartTunnelRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{17}
}

func (x *RestartTunnelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RestartTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTunnelResponse) Reset() {
	*x = RestartTunnelResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTunnelResponse) ProtoMessage() {}

func (x *RestartTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTunnelResponse.ProtoReflect.Descriptor instead.
func (*RestartTunnelResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{18}
}

func (x *RestartTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type GetTunnelLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tail          int32                  `protobuf:"varint,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelLogsRequest) Reset() {
	*x = GetTunnelLogsRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelLogsRequest) ProtoMessage() {}

func (x *GetTunnelLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelLogsRequest.ProtoReflect.Descriptor instead.
func (*GetTunnelLogsRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{19}
}

func (x *GetTunnelLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTunnelLogsRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type GetTunnelLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []string               `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelLogsResponse) Reset() {
	*x = GetTunnelLogsResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelLogsResponse) ProtoMessage() {}

func (x *GetTunnelLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelLogsResponse.ProtoReflect.Descriptor instead.
func (*GetTunnelLogsResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{20}
}

func (x *GetTunnelLogsResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type GetPlayitAccountConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayitAccountConfigRequest) Reset() {
	*x = GetPlayitAccountConfigRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayitAccountConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayitAccountConfigRequest) ProtoMessage() {}

func (x *GetPlayitAccountConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayitAccountConfigRequest.ProtoReflect.Descriptor instead.
func (*GetPlayitAccountConfigRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{21}
}

type GetPlayitAccountConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLinked      bool                   `protobuf:"varint,1,opt,name=is_linked,json=isLinked,proto3" json:"is_linked,omitempty"`
	Notice        string                 `protobuf:"bytes,2,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayitAccountConfigResponse) Reset() {
	*x = GetPlayitAccountConfigResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayitAccountConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayitAccountConfigResponse) ProtoMessage() {}

func (x *GetPlayitAccountConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayitAccountConfigResponse.ProtoReflect.Descriptor instead.
func (*GetPlayitAccountConfigResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{22}
}

func (x *GetPlayitAccountConfigResponse) GetIsLinked() bool {
	if x != nil {
		return x.IsLinked
	}
	return false
}

func (x *GetPlayitAccountConfigResponse) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

type StartAccountLinkSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAccountLinkSessionRequest) Reset() {
	*x = StartAccountLinkSessionRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAccountLinkSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAccountLinkSessionRequest) ProtoMessage() {}

func (x *StartAccountLinkSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAccountLinkSessionRequest.ProtoReflect.Descriptor instead.
func (*StartAccountLinkSessionRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{23}
}

type StartAccountLinkSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClaimUrl      string                 `protobuf:"bytes,2,opt,name=claim_url,json=claimUrl,proto3" json:"claim_url,omitempty"`
	ClaimCode     string                 `protobuf:"bytes,3,opt,name=claim_code,json=claimCode,proto3" json:"claim_code,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAccountLinkSessionResponse) Reset() {
	*x = StartAccountLinkSessionResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAccountLinkSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAccountLinkSessionResponse) ProtoMessage() {}

func (x *StartAccountLinkSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAccountLinkSessionResponse.ProtoReflect.Descriptor instead.
func (*StartAccountLinkSessionResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{24}
}

func (x *StartAccountLinkSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartAccountLinkSessionResponse) GetClaimUrl() string {
	if x != nil {
		return x.ClaimUrl
	}
	return ""
}

func (x *StartAccountLinkSessionResponse) GetClaimCode() string {
	if x != nil {
		return x.ClaimCode
	}
	return ""
}

func (x *StartAccountLinkSessionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CheckAccountLinkStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccountLinkStatusRequest) Reset() {
	*x = CheckAccountLinkStatusRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccountLinkStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccountLinkStatusRequest) ProtoMessage() {}

func (x *CheckAccountLinkStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccountLinkStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckAccountLinkStatusRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{25}
}

func (x *CheckAccountLinkStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CheckAccountLinkStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLinked      bool                   `protobuf:"varint,1,opt,name=is_linked,json=isLinked,proto3" json:"is_linked,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccountLinkStatusResponse) Reset() {
	*x = CheckAccountLinkStatusResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccountLinkStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccountLinkStatusResponse) ProtoMessage() {}

func (x *CheckAccountLinkStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccountLinkStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckAccountLinkStatusResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{26}
}

func (x *CheckAccountLinkStatusResponse) GetIsLinked() bool {
	if x != nil {
		return x.IsLinked
	}
	return false
}

func (x *CheckAccountLinkStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetPlayitAccountSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretKey     string                 `protobuf:"bytes,1,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayitAccountSecretRequest) Reset() {
	*x = SetPlayitAccountSecretRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayitAccountSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayitAccountSecretRequest) ProtoMessage() {}

func (x *SetPlayitAccountSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayitAccountSecretRequest.ProtoReflect.Descriptor instead.
func (*SetPlayitAccountSecretRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{27}
}

func (x *SetPlayitAccountSecretRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type SetPlayitAccountSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayitAccountSecretResponse) Reset() {
	*x = SetPlayitAccountSecretResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayitAccountSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayitAccountSecretResponse) ProtoMessage() {}

func (x *SetPlayitAccountSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayitAccountSecretResponse.ProtoReflect.Descriptor instead.
func (*SetPlayitAccountSecretResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{28}
}

func (x *SetPlayitAccountSecretResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnlinkPlayitAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkPlayitAccountRequest) Reset() {
	*x = UnlinkPlayitAccountRequest{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkPlayitAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkPlayitAccountRequest) ProtoMessage() {}

func (x *UnlinkPlayitAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkPlayitAccountRequest.ProtoReflect.Descriptor instead.
func (*UnlinkPlayitAccountRequest) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{29}
}

type UnlinkPlayitAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkPlayitAccountResponse) Reset() {
	*x = UnlinkPlayitAccountResponse{}
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkPlayitAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkPlayitAccountResponse) ProtoMessage() {}

func (x *UnlinkPlayitAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discopanel_v1_tunnel_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkPlayitAccountResponse.ProtoReflect.Descriptor instead.
func (*UnlinkPlayitAccountResponse) Descriptor() ([]byte, []int) {
	return file_discopanel_v1_tunnel_proto_rawDescGZIP(), []int{30}
}

func (x *UnlinkPlayitAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_discopanel_v1_tunnel_proto protoreflect.FileDescriptor

const file_discopanel_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x1adiscopanel/v1/tunnel.proto\x12\rdiscopanel.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x05\n" +
	"\x06Tunnel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\x129\n" +
	"\bprovider\x18\x04 \x01(\x0e2\x1d.discopanel.v1.TunnelProviderR\bprovider\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x129\n" +
	"\bprotocol\x18\x06 \x01(\x0e2\x1d.discopanel.v1.TunnelProtocolR\bprotocol\x12\x1f\n" +
	"\vtarget_host\x18\a \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\b \x01(\x05R\n" +
	"targetPort\x12!\n" +
	"\fcontainer_id\x18\t \x01(\tR\vcontainerId\x123\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x1b.discopanel.v1.TunnelStatusR\x06status\x12\x1b\n" +
	"\tclaim_url\x18\v \x01(\tR\bclaimUrl\x12\x1d\n" +
	"\n" +
	"claim_code\x18\f \x01(\tR\tclaimCode\x12*\n" +
	"\x11is_account_linked\x18\r \x01(\bR\x0fisAccountLinked\x12%\n" +
	"\x0epublic_address\x18\x0e \x01(\tR\rpublicAddress\x12\x1f\n" +
	"\vpublic_port\x18\x0f \x01(\x05R\n" +
	"publicPort\x12\x1d\n" +
	"\n" +
	"auto_start\x18\x10 \x01(\bR\tautoStart\x126\n" +
	"\x17follow_server_lifecycle\x18\x11 \x01(\bR\x15followServerLifecycle\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"6\n" +
	"\x17GetServerTunnelsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"y\n" +
	"\x18GetServerTunnelsResponse\x12/\n" +
	"\atunnels\x18\x01 \x03(\v2\x15.discopanel.v1.TunnelR\atunnels\x12,\n" +
	"\x12has_global_account\x18\x02 \x01(\bR\x10hasGlobalAccount\"\x14\n" +
	"\x12ListTunnelsRequest\"t\n" +
	"\x13ListTunnelsResponse\x12/\n" +
	"\atunnels\x18\x01 \x03(\v2\x15.discopanel.v1.TunnelR\atunnels\x12,\n" +
	"\x12has_global_account\x18\x02 \x01(\bR\x10hasGlobalAccount\"\"\n" +
	"\x10GetTunnelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x11GetTunnelResponse\x12-\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x15.discopanel.v1.TunnelR\x06tunnel\"\x9f\x03\n" +
	"\x13CreateTunnelRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\bprovider\x18\x03 \x01(\x0e2\x1d.discopanel.v1.TunnelProviderR\bprovider\x129\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x1d.discopanel.v1.TunnelProtocolR\bprotocol\x12\x1f\n" +
	"\vtarget_port\x18\x05 \x01(\x05R\n" +
	"targetPort\x12$\n" +
	"\vtarget_host\x18\x06 \x01(\tH\x00R\n" +
	"targetHost\x88\x01\x01\x12\"\n" +
	"\n" +
	"auto_start\x18\a \x01(\bH\x01R\tautoStart\x88\x01\x01\x12;\n" +
	"\x17follow_server_lifecycle\x18\b \x01(\bH\x02R\x15followServerLifecycle\x88\x01\x01B\x0e\n" +
	"\f_target_hostB\r\n" +
	"\v_auto_startB\x1a\n" +
	"\x18_follow_server_lifecycle\"E\n" +
	"\x14CreateTunnelResponse\x12-\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x15.discopanel.v1.TunnelR\x06tunnel\"\xd3\x01\n" +
	"\x13UpdateTunnelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"auto_start\x18\x03 \x01(\bH\x01R\tautoStart\x88\x01\x01\x12;\n" +
	"\x17follow_server_lifecycle\x18\x04 \x01(\bH\x02R\x15followServerLifecycle\x88\x01\x01B\a\n" +
	"\x05_nameB\r\n" +
	"\v_auto_startB\x1a\n" +
	"\x18_follow_server_lifecycle\"E\n" +
	"\x14UpdateTunnelResponse\x12-\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x15.discopanel.v1.TunnelR\x06tunnel\"%\n" +
	"\x13DeleteTunnelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x14DeleteTunnelResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"$\n" +
	"\x12StartTunnelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x13StartTunnelResponse\x12-\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x15.discopanel.v1.TunnelR\x06tunnel\"#\n" +
	"\x11StopTunnelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12StopTunnelResponse\x12-\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x15.discopanel.v1.TunnelR\x06tunnel\"&\n" +
	"\x14RestartTunnelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x15RestartTunnelResponse\x12-\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x15.discopanel.v1.TunnelR\x06tunnel\":\n" +
	"\x14GetTunnelLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04tail\x18\x02 \x01(\x05R\x04tail\"+\n" +
	"\x15GetTunnelLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x03(\tR\x04logs\"\x1f\n" +
	"\x1dGetPlayitAccountConfigRequest\"U\n" +
	"\x1eGetPlayitAccountConfigResponse\x12\x1b\n" +
	"\tis_linked\x18\x01 \x01(\bR\bisLinked\x12\x16\n" +
	"\x06notice\x18\x02 \x01(\tR\x06notice\" \n" +
	"\x1eStartAccountLinkSessionRequest\"\xb7\x01\n" +
	"\x1fStartAccountLinkSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclaim_url\x18\x02 \x01(\tR\bclaimUrl\x12\x1d\n" +
	"\n" +
	"claim_code\x18\x03 \x01(\tR\tclaimCode\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\">\n" +
	"\x1dCheckAccountLinkStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"U\n" +
	"\x1eCheckAccountLinkStatusResponse\x12\x1b\n" +
	"\tis_linked\x18\x01 \x01(\bR\bisLinked\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\">\n" +
	"\x1dSetPlayitAccountSecretRequest\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x01 \x01(\tR\tsecretKey\":\n" +
	"\x1eSetPlayitAccountSecretResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1c\n" +
	"\x1aUnlinkPlayitAccountRequest\"7\n" +
	"\x1bUnlinkPlayitAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*M\n" +
	"\x0eTunnelProvider\x12\x1f\n" +
	"\x1bTUNNEL_PROVIDER_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TUNNEL_PROVIDER_PLAYIT\x10\x01*\xb9\x01\n" +
	"\fTunnelStatus\x12\x1d\n" +
	"\x19TUNNEL_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TUNNEL_STATUS_STOPPED\x10\x01\x12\x1a\n" +
	"\x16TUNNEL_STATUS_STARTING\x10\x02\x12\x1f\n" +
	"\x1bTUNNEL_STATUS_CLAIM_PENDING\x10\x03\x12\x19\n" +
	"\x15TUNNEL_STATUS_RUNNING\x10\x04\x12\x17\n" +
	"\x13TUNNEL_STATUS_ERROR\x10\x05*}\n" +
	"\x0eTunnelProtocol\x12\x1f\n" +
	"\x1bTUNNEL_PROTOCOL_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TUNNEL_PROTOCOL_TCP\x10\x01\x12\x17\n" +
	"\x13TUNNEL_PROTOCOL_UDP\x10\x02\x12\x18\n" +
	"\x14TUNNEL_PROTOCOL_BOTH\x10\x032\xd3\v\n" +
	"\rTunnelService\x12c\n" +
	"\x10GetServerTunnels\x12&.discopanel.v1.GetServerTunnelsRequest\x1a'.discopanel.v1.GetServerTunnelsResponse\x12T\n" +
	"\vListTunnels\x12!.discopanel.v1.ListTunnelsRequest\x1a\".discopanel.v1.ListTunnelsResponse\x12N\n" +
	"\tGetTunnel\x12\x1f.discopanel.v1.GetTunnelRequest\x1a .discopanel.v1.GetTunnelResponse\x12W\n" +
	"\fCreateTunnel\x12\".discopanel.v1.CreateTunnelRequest\x1a#.discopanel.v1.CreateTunnelResponse\x12W\n" +
	"\fUpdateTunnel\x12\".discopanel.v1.UpdateTunnelRequest\x1a#.discopanel.v1.UpdateTunnelResponse\x12W\n" +
	"\fDeleteTunnel\x12\".discopanel.v1.DeleteTunnelRequest\x1a#.discopanel.v1.DeleteTunnelResponse\x12T\n" +
	"\vStartTunnel\x12!.discopanel.v1.StartTunnelRequest\x1a\".discopanel.v1.StartTunnelResponse\x12Q\n" +
	"\n" +
	"StopTunnel\x12 .discopanel.v1.StopTunnelRequest\x1a!.discopanel.v1.StopTunnelResponse\x12Z\n" +
	"\rRestartTunnel\x12#.discopanel.v1.RestartTunnelRequest\x1a$.discopanel.v1.RestartTunnelResponse\x12Z\n" +
	"\rGetTunnelLogs\x12#.discopanel.v1.GetTunnelLogsRequest\x1a$.discopanel.v1.GetTunnelLogsResponse\x12u\n" +
	"\x16GetPlayitAccountConfig\x12,.discopanel.v1.GetPlayitAccountConfigRequest\x1a-.discopanel.v1.GetPlayitAccountConfigResponse\x12x\n" +
	"\x17StartAccountLinkSession\x12-.discopanel.v1.StartAccountLinkSessionRequest\x1a..discopanel.v1.StartAccountLinkSessionResponse\x12u\n" +
	"\x16CheckAccountLinkStatus\x12,.discopanel.v1.CheckAccountLinkStatusRequest\x1a-.discopanel.v1.CheckAccountLinkStatusResponse\x12u\n" +
	"\x16SetPlayitAccountSecret\x12,.discopanel.v1.SetPlayitAccountSecretRequest\x1a-.discopanel.v1.SetPlayitAccountSecretResponse\x12l\n" +
	"\x13UnlinkPlayitAccount\x12).discopanel.v1.UnlinkPlayitAccountRequest\x1a*.discopanel.v1.UnlinkPlayitAccountResponseBFZDgithub.com/nickheyer/discopanel/pkg/proto/discopanel/v1;discopanelv1b\x06proto3"

var (
	file_discopanel_v1_tunnel_proto_rawDescOnce sync.Once
	file_discopanel_v1_tunnel_proto_rawDescData []byte
)

func file_discopanel_v1_tunnel_proto_rawDescGZIP() []byte {
	file_discopanel_v1_tunnel_proto_rawDescOnce.Do(func() {
		file_discopanel_v1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discopanel_v1_tunnel_proto_rawDesc), len(file_discopanel_v1_tunnel_proto_rawDesc)))
	})
	return file_discopanel_v1_tunnel_proto_rawDescData
}

var file_discopanel_v1_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_discopanel_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_discopanel_v1_tunnel_proto_goTypes = []any{
	(TunnelProvider)(0),                     // 0: discopanel.v1.TunnelProvider
	(TunnelStatus)(0),                       // 1: discopanel.v1.TunnelStatus
	(TunnelProtocol)(0),                     // 2: discopanel.v1.TunnelProtocol
	(*Tunnel)(nil),                          // 3: discopanel.v1.Tunnel
	(*GetServerTunnelsRequest)(nil),         // 4: discopanel.v1.GetServerTunnelsRequest
	(*GetServerTunnelsResponse)(nil),        // 5: discopanel.v1.GetServerTunnelsResponse
	(*ListTunnelsRequest)(nil),              // 6: discopanel.v1.ListTunnelsRequest
	(*ListTunnelsResponse)(nil),             // 7: discopanel.v1.ListTunnelsResponse
	(*GetTunnelRequest)(nil),                // 8: discopanel.v1.GetTunnelRequest
	(*GetTunnelResponse)(nil),               // 9: discopanel.v1.GetTunnelResponse
	(*CreateTunnelRequest)(nil),             // 10: discopanel.v1.CreateTunnelRequest
	(*CreateTunnelResponse)(nil),            // 11: discopanel.v1.CreateTunnelResponse
	(*UpdateTunnelRequest)(nil),             // 12: discopanel.v1.UpdateTunnelRequest
	(*UpdateTunnelResponse)(nil),            // 13: discopanel.v1.UpdateTunnelResponse
	(*DeleteTunnelRequest)(nil),             // 14: discopanel.v1.DeleteTunnelRequest
	(*DeleteTunnelResponse)(nil),            // 15: discopanel.v1.DeleteTunnelResponse
	(*StartTunnelRequest)(nil),              // 16: discopanel.v1.StartTunnelRequest
	(*StartTunnelResponse)(nil),             // 17: discopanel.v1.StartTunnelResponse
	(*StopTunnelRequest)(nil),               // 18: discopanel.v1.StopTunnelRequest
	(*StopTunnelResponse)(nil),              // 19: discopanel.v1.StopTunnelResponse
	(*RestartTunnelRequest)(nil),            // 20: discopanel.v1.RestartTunnelRequest
	(*RestartTunnelResponse)(nil),           // 21: discopanel.v1.RestartTunnelResponse
	(*GetTunnelLogsRequest)(nil),            // 22: discopanel.v1.GetTunnelLogsRequest
	(*GetTunnelLogsResponse)(nil),           // 23: discopanel.v1.GetTunnelLogsResponse
	(*GetPlayitAccountConfigRequest)(nil),   // 24: discopanel.v1.GetPlayitAccountConfigRequest
	(*GetPlayitAccountConfigResponse)(nil),  // 25: discopanel.v1.GetPlayitAccountConfigResponse
	(*StartAccountLinkSessionRequest)(nil),  // 26: discopanel.v1.StartAccountLinkSessionRequest
	(*StartAccountLinkSessionResponse)(nil), // 27: discopanel.v1.StartAccountLinkSessionResponse
	(*CheckAccountLinkStatusRequest)(nil),   // 28: discopanel.v1.CheckAccountLinkStatusRequest
	(*CheckAccountLinkStatusResponse)(nil),  // 29: discopanel.v1.CheckAccountLinkStatusResponse
	(*SetPlayitAccountSecretRequest)(nil),   // 30: discopanel.v1.SetPlayitAccountSecretRequest
	(*SetPlayitAccountSecretResponse)(nil),  // 31: discopanel.v1.SetPlayitAccountSecretResponse
	(*UnlinkPlayitAccountRequest)(nil),      // 32: discopanel.v1.UnlinkPlayitAccountRequest
	(*UnlinkPlayitAccountResponse)(nil),     // 33: discopanel.v1.UnlinkPlayitAccountResponse
	(*timestamppb.Timestamp)(nil),           // 34: google.protobuf.Timestamp
}
var file_discopanel_v1_tunnel_proto_depIdxs = []int32{
	0,  // 0: discopanel.v1.Tunnel.provider:type_name -> discopanel.v1.TunnelProvider
	2,  // 1: discopanel.v1.Tunnel.protocol:type_name -> discopanel.v1.TunnelProtocol
	1,  // 2: discopanel.v1.Tunnel.status:type_name -> discopanel.v1.TunnelStatus
	34, // 3: discopanel.v1.Tunnel.created_at:type_name -> google.protobuf.Timestamp
	34, // 4: discopanel.v1.Tunnel.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 5: discopanel.v1.GetServerTunnelsResponse.tunnels:type_name -> discopanel.v1.Tunnel
	3,  // 6: discopanel.v1.ListTunnelsResponse.tunnels:type_name -> discopanel.v1.Tunnel
	3,  // 7: discopanel.v1.GetTunnelResponse.tunnel:type_name -> discopanel.v1.Tunnel
	0,  // 8: discopanel.v1.CreateTunnelRequest.provider:type_name -> discopanel.v1.TunnelProvider
	2,  // 9: discopanel.v1.CreateTunnelRequest.protocol:type_name -> discopanel.v1.TunnelProtocol
	3,  // 10: discopanel.v1.CreateTunnelResponse.tunnel:type_name -> discopanel.v1.Tunnel
	3,  // 11: discopanel.v1.UpdateTunnelResponse.tunnel:type_name -> discopanel.v1.Tunnel
	3,  // 12: discopanel.v1.StartTunnelResponse.tunnel:type_name -> discopanel.v1.Tunnel
	3,  // 13: discopanel.v1.StopTunnelResponse.tunnel:type_name -> discopanel.v1.Tunnel
	3,  // 14: discopanel.v1.RestartTunnelResponse.tunnel:type_name -> discopanel.v1.Tunnel
	34, // 15: discopanel.v1.StartAccountLinkSessionResponse.expires_at:type_name -> google.protobuf.Timestamp
	4,  // 16: discopanel.v1.TunnelService.GetServerTunnels:input_type -> discopanel.v1.GetServerTunnelsRequest
	6,  // 17: discopanel.v1.TunnelService.ListTunnels:input_type -> discopanel.v1.ListTunnelsRequest
	8,  // 18: discopanel.v1.TunnelService.GetTunnel:input_type -> discopanel.v1.GetTunnelRequest
	10, // 19: discopanel.v1.TunnelService.CreateTunnel:input_type -> discopanel.v1.CreateTunnelRequest
	12, // 20: discopanel.v1.TunnelService.UpdateTunnel:input_type -> discopanel.v1.UpdateTunnelRequest
	14, // 21: discopanel.v1.TunnelService.DeleteTunnel:input_type -> discopanel.v1.DeleteTunnelRequest
	16, // 22: discopanel.v1.TunnelService.StartTunnel:input_type -> discopanel.v1.StartTunnelRequest
	18, // 23: discopanel.v1.TunnelService.StopTunnel:input_type -> discopanel.v1.StopTunnelRequest
	20, // 24: discopanel.v1.TunnelService.RestartTunnel:input_type -> discopanel.v1.RestartTunnelRequest
	22, // 25: discopanel.v1.TunnelService.GetTunnelLogs:input_type -> discopanel.v1.GetTunnelLogsRequest
	24, // 26: discopanel.v1.TunnelService.GetPlayitAccountConfig:input_type -> discopanel.v1.GetPlayitAccountConfigRequest
	26, // 27: discopanel.v1.TunnelService.StartAccountLinkSession:input_type -> discopanel.v1.StartAccountLinkSessionRequest
	28, // 28: discopanel.v1.TunnelService.CheckAccountLinkStatus:input_type -> discopanel.v1.CheckAccountLinkStatusRequest
	30, // 29: discopanel.v1.TunnelService.SetPlayitAccountSecret:input_type -> discopanel.v1.SetPlayitAccountSecretRequest
	32, // 30: discopanel.v1.TunnelService.UnlinkPlayitAccount:input_type -> discopanel.v1.UnlinkPlayitAccountRequest
	5,  // 31: discopanel.v1.TunnelService.GetServerTunnels:output_type -> discopanel.v1.GetServerTunnelsResponse
	7,  // 32: discopanel.v1.TunnelService.ListTunnels:output_type -> discopanel.v1.ListTunnelsResponse
	9,  // 33: discopanel.v1.TunnelService.GetTunnel:output_type -> discopanel.v1.GetTunnelResponse
	11, // 34: discopanel.v1.TunnelService.CreateTunnel:output_type -> discopanel.v1.CreateTunnelResponse
	13, // 35: discopanel.v1.TunnelService.UpdateTunnel:output_type -> discopanel.v1.UpdateTunnelResponse
	15, // 36: discopanel.v1.TunnelService.DeleteTunnel:output_type -> discopanel.v1.DeleteTunnelResponse
	17, // 37: discopanel.v1.TunnelService.StartTunnel:output_type -> discopanel.v1.StartTunnelResponse
	19, // 38: discopanel.v1.TunnelService.StopTunnel:output_type -> discopanel.v1.StopTunnelResponse
	21, // 39: discopanel.v1.TunnelService.RestartTunnel:output_type -> discopanel.v1.RestartTunnelResponse
	23, // 40: discopanel.v1.TunnelService.GetTunnelLogs:output_type -> discopanel.v1.GetTunnelLogsResponse
	25, // 41: discopanel.v1.TunnelService.GetPlayitAccountConfig:output_type -> discopanel.v1.GetPlayitAccountConfigResponse
	27, // 42: discopanel.v1.TunnelService.StartAccountLinkSession:output_type -> discopanel.v1.StartAccountLinkSessionResponse
	29, // 43: discopanel.v1.TunnelService.CheckAccountLinkStatus:output_type -> discopanel.v1.CheckAccountLinkStatusResponse
	31, // 44: discopanel.v1.TunnelService.SetPlayitAccountSecret:output_type -> discopanel.v1.SetPlayitAccountSecretResponse
	33, // 45: discopanel.v1.TunnelService.UnlinkPlayitAccount:output_type -> discopanel.v1.UnlinkPlayitAccountResponse
	31, // [31:46] is the sub-list for method output_type
	16, // [16:31] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_discopanel_v1_tunnel_proto_init() }
func file_discopanel_v1_tunnel_proto_init() {
	if File_discopanel_v1_tunnel_proto != nil {
		return
	}
	file_discopanel_v1_tunnel_proto_msgTypes[7].OneofWrappers = []any{}
	file_discopanel_v1_tunnel_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discopanel_v1_tunnel_proto_rawDesc), len(file_discopanel_v1_tunnel_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discopanel_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_discopanel_v1_tunnel_proto_depIdxs,
		EnumInfos:         file_discopanel_v1_tunnel_proto_enumTypes,
		MessageInfos:      file_discopanel_v1_tunnel_proto_msgTypes,
	}.Build()
	File_discopanel_v1_tunnel_proto = out.File
	file_discopanel_v1_tunnel_proto_goTypes = nil
	file_discopanel_v1_tunnel_proto_depIdxs = nil
}
